version = 1

[[annotations]]
path = [
  "src/**",
  "tests/**",
  "pyproject.toml",
  "uv.lock",
  "README.md",
  "docs/**",
  ".gitignore",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Boris Peyriguere and Complexity-ML"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "data/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Boris Peyriguere and Complexity-ML"
SPDX-License-Identifier = "CC-BY-NC-4.0"
