from __future__ import annotations


_TASK_TEMPLATES: dict[str, tuple[str, ...]] = {
    "state_goal": (
        "{goal}",
        "Can you help me think this through? {goal}",
        "I want to make a practical choice. {goal}",
        "I could use a clear plan here: {goal_lower}",
        "Please help me narrow this down. {goal}",
        "I am trying to decide what to do next. {goal}",
        "Here is what I need help with: {goal_lower}",
        "Could we work through one decision? {goal}",
        "Could you help me choose a sensible next step? {goal}",
        "I would like a second opinion before I act. {goal}",
    ),
    "acknowledge_goal": (
        "{acknowledgement}",
        "Understood. {acknowledgement}",
        "That is a clear goal. {acknowledgement}",
        "That gives us a clear scope. {acknowledgement}",
        "Yes. {acknowledgement}",
        "Let us make the trade-off explicit. {acknowledgement}",
        "I follow the decision you are trying to make. {acknowledgement}",
        "We can approach this without guessing. {acknowledgement}",
    ),
    "provide_detail": (
        "{detail}",
        "One useful detail is this: {detail_lower}",
        "For context, {detail_lower}",
        "The main constraint is that {detail_lower}",
        "There is one more thing to account for: {detail_lower}",
        "The relevant background is this: {detail_lower}",
        "A constraint that may change the answer is that {detail_lower}",
        "Here is the detail I do not want to lose: {detail_lower}",
    ),
    "ask_for_missing_detail": (
        "{question}",
        "Before comparing the options, {question_lower}",
        "One detail would change the recommendation: {question_lower}",
        "To avoid guessing, {question_lower}",
        "I need one point clarified. {question}",
        "A reliable answer depends on one fact. {question}",
        "Let us check the missing condition first. {question}",
        "The safest comparison starts with this question: {question_lower}",
    ),
    "choose_option": (
        "{priority}",
        "My priority is simple: {priority_lower}",
        "The deciding factor for me is that {priority_lower}",
        "I would rather optimize for this: {priority_lower}",
        "What matters most is that {priority_lower}",
        "I can make the trade-off if we preserve this: {priority_lower}",
        "My preference should follow one rule: {priority_lower}",
        "The outcome I care about is clear: {priority_lower}",
    ),
    "present_bounded_options": (
        "Two sensible options are {option_a} or {option_b}.",
        "I would compare only two paths: {option_a}, and {option_b}.",
        "The practical shortlist is {option_a} versus {option_b}.",
        "You can keep the decision bounded: choose between {option_a} and {option_b}.",
        "Given that priority, the realistic choices are {option_a} or {option_b}.",
        "That leaves a short comparison: {option_a}, or instead {option_b}.",
        "There is no need for a long list; compare {option_a} with {option_b}.",
        "On those terms, compare {option_a} directly with {option_b}.",
    ),
    "confirm_choice": (
        "{choice}",
        "I will go with this: {choice_lower}",
        "The first option fits better. {choice}",
        "That makes the decision easier. {choice}",
        "I have made the choice: {choice_lower}",
        "That settles it for me. {choice}",
        "I know which direction fits now. {choice}",
        "I am comfortable choosing on that basis. {choice}",
    ),
    "confirm_next_step": (
        "{next_step}",
        "Good. {next_step}",
        "That is a workable decision. {next_step}",
        "The next step is now clear. {next_step}",
        "You have a bounded plan. {next_step}",
        "You can act on that choice without adding more options. {next_step}",
        "That completes the decision. {next_step}",
        "The plan is specific enough to use. {next_step}",
    ),
    "give_direct_next_step": (
        "{next_step}",
        "A practical first step is simple: {next_step_lower}",
        "Start here: {next_step_lower}",
        "The immediate action is to {next_step_lower}",
        "For now, {next_step_lower}",
        "Keep it concrete: {next_step_lower}",
        "The most useful first move is to {next_step_lower}",
        "Without adding more options, {next_step_lower}",
    ),
    "request_written_confirmation": (
        "Before committing, ask the provider to confirm this in writing: {question}",
        "Get one written answer before proceeding: {question}",
        "Ask for a written reply to the decisive question: {question}",
        "Keep the commitment conditional until this is answered in writing: {question}",
        "The useful written confirmation is a direct answer to this: {question}",
        "Request written confirmation rather than relying on the listing: {question}",
        "Use one written check before booking or paying: {question}",
        "Have the provider answer this in writing before you commit: {question}",
    ),
    "give_recorded_reason": (
        "{recommendation} Record the stated priority and the constraint behind it.",
        "Use this bounded choice: {recommendation_lower} Write down which requirement it satisfies.",
        "The recommendation is specific: {recommendation_lower} Keep a short note of the deciding fact.",
        "Choose on the available evidence: {recommendation_lower} Record what would change the decision.",
        "A reviewable decision is possible: {recommendation_lower} Note the priority and supporting fact.",
        "Make the choice explicit: {recommendation_lower} Then record the reason in one sentence.",
        "Keep the rationale attached to the action: {recommendation_lower} Note the decisive condition.",
        "Use the stated priority as the record: {recommendation_lower} Write down the decisive constraint.",
    ),
    "give_choice_and_action": (
        "{recommendation} {next_step}",
        "The bounded choice is this: {recommendation_lower} Then {next_step_lower}",
        "Make one decision and act on it: {recommendation_lower} Next, {next_step_lower}",
        "Choose a single path: {recommendation_lower} The immediate action is to {next_step_lower}",
        "The recommendation is to {recommendation_lower} Follow it by taking this step: {next_step_lower}",
        "Use this choice: {recommendation_lower} Then complete the concrete next step: {next_step_lower}",
        "Keep the result specific: {recommendation_lower} After that, {next_step_lower}",
        "Finish with this choice: {recommendation_lower} Act now by doing the following: {next_step_lower}",
    ),
    "offer_safe_alternative": (
        "{safe_alternative}",
        "A safer fallback is available: {safe_alternative_lower}",
        "I cannot confirm the preferred option from here. As a fallback, {safe_alternative_lower}",
        "If the preferred path is unavailable, {safe_alternative_lower}",
        "To avoid overpromising, use this fallback: {safe_alternative_lower}",
        "A cautious alternative would be to {safe_alternative_lower}",
        "There is a practical fallback that avoids an unsupported promise: {safe_alternative_lower}",
        "When the preferred option cannot be confirmed, {safe_alternative_lower}",
    ),
}


_EMPATHY_TEMPLATES: dict[str, tuple[str, ...]] = {
    "share_situation": (
        "{situation}",
        "I have been trying to put this into words. {situation}",
        "I could use a calm perspective. {situation}",
        "Something has been sitting with me. {situation}",
        "I want to talk through something ordinary but important. {situation}",
        "I am still making sense of a feeling. {situation}",
        "This has been on my mind today. {situation}",
        "I would like to say this out loud. {situation}",
    ),
    "acknowledge_emotion": (
        "{acknowledgement}",
        "That reaction makes sense. {acknowledgement}",
        "I can see why this stayed with you. {acknowledgement}",
        "It sounds like this matters a lot. {acknowledgement}",
        "There is a real reason this affected you. {acknowledgement}",
        "Your response fits what happened. {acknowledgement}",
        "That carries more weight than it may seem from outside. {acknowledgement}",
        "I hear how strongly this landed. {acknowledgement}",
    ),
    "expand_feeling": (
        "{detail}",
        "The part I keep returning to is this: {detail_lower}",
        "What makes it harder is that {detail_lower}",
        "I think the feeling is stronger because {detail_lower}",
        "There is another layer to it. {detail}",
        "I notice one detail keeps intensifying it: {detail_lower}",
        "The feeling is tied to something specific. {detail}",
        "What stays with me is that {detail_lower}",
    ),
    "invite_detail_without_assumption": (
        "{question}",
        "If you want to unpack it, {question_lower}",
        "We do not have to assume the answer. {question}",
        "It may help to name the important part. {question}",
        "You can decide how much to explore. {question}",
        "A useful distinction might be available here. {question}",
        "We can stay close to what you actually know. {question}",
        "One gentle question may clarify the feeling. {question}",
    ),
    "reflect_on_need": (
        "{need}",
        "I think what I need is straightforward: {need_lower}",
        "Putting it plainly, {need_lower}",
        "The useful outcome for me would be this: {need_lower}",
        "I can name the need more clearly now. {need}",
        "What I am asking from this moment is simple: {need_lower}",
        "There is a practical need under the feeling. {need}",
        "I do not need a complete solution; {need_lower}",
    ),
    "offer_grounded_support": (
        "{support}",
        "A small, grounded step could help. {support}",
        "You do not need to solve everything at once. {support}",
        "Keeping it manageable may be best. {support}",
        "The response can stay small and concrete. {support}",
        "A measured next step is enough for now. {support}",
        "You can support yourself without forcing a quick resolution. {support}",
        "It may help to work with what is within reach. {support}",
    ),
    "follow_up": (
        "{follow_up}",
        "That feels manageable. {follow_up}",
        "I can start there. {follow_up}",
        "That gives me something concrete to try. {follow_up}",
        "I know where to begin now. {follow_up}",
        "That is specific enough to use. {follow_up}",
        "I can carry that into the next moment. {follow_up}",
        "The next step feels clearer. {follow_up}",
    ),
    "close_supportively": (
        "{closing}",
        "That sounds like a thoughtful next step. {closing}",
        "You have given this careful thought. {closing}",
        "There is no need to rush the rest. {closing}",
        "That is a kind and realistic place to stop. {closing}",
        "You can let this understanding settle. {closing}",
        "Nothing more has to be decided right now. {closing}",
        "The next step can remain modest. {closing}",
    ),
}


_TASK_FRAMES: dict[str, tuple[str, ...]] = {
    "state_goal": (
        "{}",
        "For now, {}",
        "In practical terms, {}",
        "Before I decide, {}",
    ),
    "acknowledge_goal": (
        "{}",
        "In that case, {}",
        "Keeping the scope narrow, {}",
        "On that basis, {}",
    ),
    "provide_detail": (
        "{}",
        "More specifically, {}",
        "The context is simple: {}",
        "One point matters here: {}",
    ),
    "ask_for_missing_detail": (
        "{}",
        "To narrow it down, {}",
        "Before moving on, {}",
        "The deciding question is this: {}",
    ),
    "choose_option": (
        "{}",
        "For the final choice, {}",
        "Looking at the trade-off, {}",
        "To keep the decision clear, {}",
    ),
    "present_bounded_options": (
        "{}",
        "Within that boundary, {}",
        "For a short comparison, {}",
        "Keeping only realistic choices, {}",
    ),
    "confirm_choice": (
        "{}",
        "With that comparison made, {}",
        "The choice is now specific: {}",
        "Based on the stated priority, {}",
    ),
    "confirm_next_step": (
        "{}",
        "From here, {}",
        "To complete the plan, {}",
        "For the immediate next step, {}",
    ),
    "give_direct_next_step": (
        "{}",
        "As a first step, {}",
        "To make progress, {}",
        "For one concrete action, {}",
    ),
    "request_written_confirmation": (
        "{}",
        "Before any commitment, {}",
        "For a verifiable answer, {}",
        "To keep a written record, {}",
    ),
    "give_recorded_reason": (
        "{}",
        "For a reviewable decision, {}",
        "To preserve the rationale, {}",
        "For a short decision record, {}",
    ),
    "give_choice_and_action": (
        "{}",
        "To finish the decision, {}",
        "For one choice and one action, {}",
        "Keeping the result concrete, {}",
    ),
    "offer_safe_alternative": (
        "{}",
        "If confirmation is unavailable, {}",
        "To keep the fallback bounded, {}",
        "Without making an unsupported assumption, {}",
    ),
}


_EMPATHY_FRAMES: dict[str, tuple[str, ...]] = {
    "share_situation": (
        "{}",
        "Right now, {}",
        "Said plainly, {}",
        "What I notice is this: {}",
    ),
    "acknowledge_emotion": (
        "{}",
        "Without rushing the feeling, {}",
        "Seen in context, {}",
        "Staying close to what happened, {}",
    ),
    "expand_feeling": (
        "{}",
        "Looking at it more closely, {}",
        "There is room for one more detail: {}",
        "As the feeling settles, {}",
    ),
    "invite_detail_without_assumption": (
        "{}",
        "Without deciding for you, {}",
        "If it feels useful, {}",
        "To understand rather than assume, {}",
    ),
    "reflect_on_need": (
        "{}",
        "Underneath the reaction, {}",
        "For the present moment, {}",
        "Keeping the need modest, {}",
    ),
    "offer_grounded_support": (
        "{}",
        "As a grounded response, {}",
        "Without trying to fix everything, {}",
        "For one manageable step, {}",
    ),
    "follow_up": (
        "{}",
        "With that in mind, {}",
        "For the next small step, {}",
        "Leaving room to adjust, {}",
    ),
    "close_supportively": (
        "{}",
        "For now, {}",
        "Without forcing a conclusion, {}",
        "As a place to pause, {}",
    ),
}
