from __future__ import annotations


GENERAL_FACTS = (
    ("geography", "What is the capital of Italy?", "Rome", "Rome is the seat of Italy's national government."),
    ("geography", "What is the capital of Spain?", "Madrid", "Madrid is located near the geographic center of Spain."),
    ("geography", "What is the capital of Japan?", "Tokyo", "Tokyo is Japan's largest metropolitan area."),
    ("geography", "What is the capital of Canada?", "Ottawa", "Ottawa is in the province of Ontario."),
    ("geography", "What is the capital of Australia?", "Canberra", "Canberra lies in the Australian Capital Territory."),
    ("geography", "Which ocean is the largest on Earth?", "the Pacific Ocean", "It covers more area than any other ocean."),
    ("geography", "Which continent contains the Sahara Desert?", "Africa", "The Sahara spans much of northern Africa."),
    ("geography", "Which river flows through Egypt into the Mediterranean Sea?", "the Nile", "The Nile has supported settlements in Egypt for millennia."),
    ("astronomy", "Which planet is closest to the Sun?", "Mercury", "Mercury completes one orbit faster than any other planet."),
    ("astronomy", "Which planet is the largest in the Solar System?", "Jupiter", "Jupiter is a gas giant with a mass greater than all other planets combined."),
    ("astronomy", "What is Earth's natural satellite called?", "the Moon", "The Moon's gravity is the main driver of Earth's ocean tides."),
    ("astronomy", "Which star is at the center of the Solar System?", "the Sun", "The Sun contains most of the Solar System's mass."),
    ("biology", "What process lets plants convert light energy into chemical energy?", "photosynthesis", "Plants use light, water, and carbon dioxide during this process."),
    ("biology", "Which gas do humans take in for cellular respiration?", "oxygen", "Cells use oxygen to release energy from nutrients."),
    ("biology", "What molecule carries hereditary information in most living organisms?", "DNA", "DNA stores genetic instructions in sequences of nucleotides."),
    ("biology", "Which organ pumps blood through the human body?", "the heart", "Its contractions move blood through the circulatory system."),
    ("chemistry", "What is the chemical formula for water?", "H2O", "Each molecule contains two hydrogen atoms and one oxygen atom."),
    ("chemistry", "What is the chemical symbol for gold?", "Au", "The symbol comes from the Latin word aurum."),
    ("chemistry", "Which pH value is neutral at room temperature?", "7", "Pure water is approximately neutral at room temperature."),
    ("chemistry", "What gas is represented by the formula CO2?", "carbon dioxide", "Each molecule contains one carbon atom and two oxygen atoms."),
    ("physics", "What SI unit measures electric current?", "the ampere", "The unit is commonly abbreviated as A."),
    ("physics", "What force attracts objects toward Earth?", "gravity", "Gravity gives objects weight near Earth's surface."),
    ("physics", "What SI unit measures force?", "the newton", "One newton accelerates one kilogram by one meter per second squared."),
    ("physics", "Can sound travel through a vacuum?", "no", "Sound requires matter through which its mechanical vibration can propagate."),
    ("mathematics", "How many degrees are in a right angle?", "90 degrees", "A right angle is one quarter of a full rotation."),
    ("mathematics", "How many sides does a hexagon have?", "six", "The prefix hex- denotes six."),
    ("mathematics", "What is the only even prime number?", "2", "Every other even integer is divisible by both 1 and 2 and is therefore composite."),
    ("mathematics", "What is the square root of 81?", "9", "Nine multiplied by nine equals 81."),
    ("computing", "What does CPU stand for?", "central processing unit", "The CPU executes instructions and coordinates many computer operations."),
    ("computing", "What does RAM stand for?", "random-access memory", "RAM holds data that active programs need quickly."),
    ("computing", "How many bits are in one byte?", "eight", "A byte conventionally contains eight binary digits."),
    ("computing", "What does URL stand for?", "uniform resource locator", "A URL identifies the location of a resource on a network."),
    ("computing", "Which two digits does the binary numeral system use?", "0 and 1", "Binary represents values with powers of two."),
    ("computing", "What protocol secures ordinary HTTP traffic with encryption?", "HTTPS", "HTTPS uses TLS to protect data in transit."),
    ("history", "In which year did the first human land on the Moon?", "1969", "Apollo 11 landed on the Moon in July of that year."),
    ("history", "Which ancient civilization built Machu Picchu?", "the Inca", "The site was built in the Andes in the fifteenth century."),
    ("history", "Who wrote the United States Declaration of Independence's principal draft?", "Thomas Jefferson", "Congress revised the draft before adopting it in 1776."),
    ("history", "Which city was buried by Mount Vesuvius in 79 CE?", "Pompeii", "Volcanic material preserved much of the Roman city."),
    ("literature", "Who wrote Pride and Prejudice?", "Jane Austen", "The novel was first published in 1813."),
    ("literature", "Who wrote Romeo and Juliet?", "William Shakespeare", "The work is one of Shakespeare's tragedies."),
    ("art", "Who painted the Mona Lisa?", "Leonardo da Vinci", "The portrait is displayed at the Louvre in Paris."),
    ("music", "How many semitones are in a standard Western octave?", "twelve", "The twelfth semitone returns to the same pitch class."),
    ("language", "What punctuation mark normally ends a direct question?", "a question mark", "In English, it is written as a question mark after the question."),
    ("language", "What is the plural of child?", "children", "Children is an irregular English plural."),
    ("time", "How many minutes are in one hour?", "60", "Each hour is divided into sixty minutes."),
    ("time", "How many hours are in one day?", "24", "A civil day is divided into twenty-four hours."),
    ("measurement", "How many meters are in one kilometer?", "1,000", "The prefix kilo- means one thousand."),
    ("measurement", "How many centimeters are in one meter?", "100", "The prefix centi- means one hundredth."),
    ("earth_science", "What instrument records earthquakes?", "a seismograph", "It records ground motion produced by seismic waves."),
    ("earth_science", "What is molten rock beneath Earth's surface called?", "magma", "Once it reaches the surface, molten rock is called lava."),
)


CONCEPTS = (
    ("statistics", "mean", "the sum of a set of values divided by the number of values", "the mean of 2, 4, and 6 is 4", "Unlike the median, the mean uses every value's magnitude"),
    ("statistics", "median", "the middle value after observations are ordered", "the median of 2, 9, and 20 is 9", "Unlike the mean, it is less affected by an extreme value"),
    ("statistics", "probability", "a measure of how likely an event is", "a fair coin gives heads a probability of one half", "It describes uncertainty rather than guaranteeing one outcome"),
    ("statistics", "correlation", "a pattern in how two measured variables change together", "temperature and ice-cream sales may rise together", "Correlation alone does not establish causation"),
    ("machine_learning", "precision", "the share of predicted positive cases that are actually positive", "eight correct alerts among ten alerts gives precision of eighty percent", "Recall instead measures how many actual positives were found"),
    ("machine_learning", "recall", "the share of actual positive cases that a system identifies", "finding nine of ten faulty parts gives recall of ninety percent", "Precision instead evaluates the reliability of positive predictions"),
    ("machine_learning", "overfitting", "learning training details so narrowly that performance degrades on new data", "a model memorizes sample noise but misses the broader pattern", "Good training fit alone is not proof of generalization"),
    ("machine_learning", "embedding", "a numeric vector used to represent an item in a learned space", "similar words can receive nearby vectors", "An embedding is a representation, not the original item itself"),
    ("computing", "algorithm", "a finite procedure for transforming inputs into an intended result", "binary search repeatedly halves a sorted search range", "An algorithm is the method, while a program is one implementation"),
    ("computing", "cache", "fast storage that keeps data likely to be needed again", "a browser retains a local copy of an image", "A cache improves access speed but is not the authoritative source"),
    ("computing", "database index", "a structure that speeds retrieval by organizing lookup information", "an index on customer ID avoids scanning every record", "It accelerates reads but adds storage and update cost"),
    ("computing", "encryption", "transforming readable data into a form accessible only with the proper key", "HTTPS encrypts traffic between a browser and a server", "Encryption protects content, whereas hashing is designed as a one-way transformation"),
    ("networks", "latency", "the time required for data or an action to travel from source to destination", "a request takes forty milliseconds to reach a server and return", "Bandwidth measures capacity rather than delay"),
    ("networks", "bandwidth", "the amount of data a connection can carry per unit of time", "a link transfers one gigabit each second", "High bandwidth does not necessarily imply low latency"),
    ("software", "idempotence", "the property that repeating an operation has the same effect as performing it once", "setting a status to closed twice leaves it closed", "It differs from an operation whose effect accumulates on every call"),
    ("software", "regression test", "a test that checks whether an existing behavior still works after a change", "a fixed bug receives a test that must keep passing", "It protects known behavior rather than discovering every unknown defect"),
    ("logic", "deduction", "reasoning in which a conclusion follows necessarily from stated premises", "all mammals breathe and whales are mammals, so whales breathe", "Induction supports a likely generalization rather than a necessary conclusion"),
    ("logic", "contradiction", "a pair of claims that cannot both be true in the same respect", "a door cannot be both fully open and not open at the same moment", "A disagreement is not automatically a formal contradiction"),
    ("planning", "constraint", "a condition that limits which solutions are acceptable", "a delivery must arrive before noon and stay under budget", "A preference can be traded off, while a hard constraint cannot"),
    ("planning", "dependency", "a relationship in which one task requires another result first", "testing depends on a completed build", "A dependency determines order rather than merely indicating importance"),
    ("economics", "opportunity cost", "the value of the best alternative given up when a choice is made", "attending a course may cost the work one could have done then", "It includes forgone alternatives, not only money paid"),
    ("economics", "inflation", "a sustained increase in the general price level over time", "the same basket of goods costs more than a year earlier", "A single product becoming expensive is not by itself general inflation"),
    ("finance", "compound interest", "interest calculated on both the original amount and previously earned interest", "savings earn interest this year on last year's added interest", "Simple interest is calculated only on the original principal"),
    ("finance", "diversification", "spreading exposure across different assets or risks", "an investor holds several sectors rather than one company", "It can reduce specific risk but cannot remove every market risk"),
    ("science", "hypothesis", "a testable proposed explanation for an observation", "a researcher predicts that added light increases plant growth", "A hypothesis is evaluated with evidence rather than accepted as a fact"),
    ("science", "control group", "a comparison group that does not receive the tested intervention", "one group receives a new treatment while the control receives standard care", "It provides a baseline for interpreting the treatment group"),
    ("physics", "inertia", "the tendency of an object's motion to remain unchanged unless a net force acts", "a book stays at rest until something pushes it", "Inertia is a property of matter, not a separate force"),
    ("physics", "energy", "the capacity of a system to produce change or perform work", "a raised object has gravitational potential energy", "Energy can change form even when total energy is conserved"),
    ("biology", "ecosystem", "a community of organisms interacting with each other and their physical environment", "a pond includes microbes, plants, animals, water, and nutrients", "A habitat is the place an organism lives, while an ecosystem includes interactions"),
    ("biology", "homeostasis", "the regulation of internal conditions within a viable range", "sweating helps control body temperature", "It maintains dynamic stability rather than an unchanging state"),
    ("language", "metaphor", "a figure of speech that describes one thing as another to suggest a likeness", "calling time a thief emphasizes how it takes moments away", "A simile usually marks the comparison with like or as"),
    ("language", "active voice", "a construction in which the grammatical subject performs the action", "the sentence ‘The team approved the proposal’ uses active voice", "Passive voice makes the receiver of the action the subject"),
    ("writing", "thesis statement", "a sentence that presents the central claim an argument will support", "an essay states that urban trees reduce heat and improve health", "A topic names the subject, while a thesis makes a specific claim"),
    ("writing", "summary", "a shorter account that preserves the source's main ideas", "a paragraph condenses a report's finding and recommendation", "A summary reduces detail without adding a new argument"),
    ("security", "phishing", "an attempt to trick someone into revealing information or taking an unsafe action", "a fake login email asks for a password", "It relies on deception rather than legitimate account support"),
    ("security", "multi-factor authentication", "requiring evidence from more than one authentication factor", "a login uses a password and a hardware key", "Two passwords are still the same factor type"),
    ("project_management", "milestone", "a significant checkpoint used to track progress", "approval of a prototype marks the end of a project phase", "A milestone marks an event and usually has no duration of its own"),
    ("project_management", "scope creep", "uncontrolled expansion of work beyond the agreed boundaries", "new features keep entering a release without time or budget changes", "A formally approved scope change is not uncontrolled creep"),
    ("ethics", "conflict of interest", "a situation in which competing interests could compromise judgment", "a reviewer evaluates a company they own shares in", "Disclosure manages the risk but does not erase the competing interest"),
    ("communication", "feedback loop", "a cycle in which results are observed and used to adjust later action", "a team measures errors and changes its process in response", "One-way reporting lacks the adjustment that closes the loop"),
)


__all__ = ("CONCEPTS", "GENERAL_FACTS")
