from __future__ import annotations


# Each fact has a source-facing and answer-facing realization.  The answer
# therefore preserves meaning without teaching extractive prompt copying.
SUMMARY_CASES = (
    (
        "operations",
        "a ventilation fault interrupted the morning room inspection",
        "the morning inspection stopped when the ventilation system failed",
        "replaced a loose fan guard and repeated the safety check",
        "secured the fan guard before running the safety inspection again",
        "the room reopened with normal airflow",
        "normal airflow was restored and the room returned to service",
        "add guard clearance to the monthly checklist",
        "include fan-guard clearance in the monthly inspection",
    ),
    (
        "operations",
        "two workshops were assigned to the same room",
        "a scheduling conflict placed two workshops in one room",
        "moved the smaller workshop and corrected the shared calendar",
        "relocated the smaller session and repaired the common schedule",
        "both sessions started on time",
        "neither workshop was delayed",
        "enable conflict alerts for recurring bookings",
        "turn on collision warnings for repeating reservations",
    ),
    (
        "logistics",
        "a medical parcel missed its transfer scan",
        "a clinic shipment moved without a recorded transfer",
        "located it in the inbound cage and restored its tracking entry",
        "found the parcel in receiving and repaired its tracking history",
        "the parcel reached the clinic that afternoon",
        "the clinic received the shipment before the day ended",
        "require a scan before cages are moved",
        "confirm tracking before any receiving cage changes location",
    ),
    (
        "logistics",
        "an inventory count differed from the ordering system",
        "the shelf total disagreed with the purchasing record",
        "recounted the sealed stock and removed a duplicated receipt",
        "verified the unopened stock and deleted the repeated intake record",
        "the verified balance matched the shelves",
        "the corrected system total agreed with the physical stock",
        "review automated receipts before replenishment",
        "check imported intake records before placing another order",
    ),
    (
        "training",
        "new staff could not follow the outdated login guide",
        "an obsolete access guide blocked new employees from signing in",
        "rewrote the access steps and tested them with a new starter",
        "updated the instructions and validated them with a recent hire",
        "the next group completed setup without assistance",
        "later starters activated their accounts independently",
        "review the guide after every account-system change",
        "recheck the instructions whenever the account platform changes",
    ),
    (
        "training",
        "a workshop left no time for practice",
        "the session ended before participants could apply the lesson",
        "shortened the lecture and added a guided exercise",
        "reduced presentation time and introduced supervised practice",
        "participants completed the core task during the session",
        "attendees performed the essential task before leaving",
        "reserve one third of future sessions for practice",
        "protect a third of each later workshop for hands-on work",
    ),
    (
        "research",
        "field readings varied after equipment transport",
        "moving the instrument made its measurements inconsistent",
        "recalibrated the optical sensor before each location",
        "reset the sensor calibration at every new site",
        "the repeated measurements became consistent",
        "successive readings aligned after the change",
        "log calibration values with every site visit",
        "record the calibration state for each field location",
    ),
    (
        "research",
        "the survey report mixed quotations with interpretation",
        "participant statements and analyst conclusions were interleaved",
        "separated participant statements from analyst conclusions",
        "placed raw quotations and analysis in distinct sections",
        "reviewers could trace each conclusion to evidence",
        "readers could connect every interpretation to its source",
        "use distinct evidence and analysis sections",
        "keep source material apart from interpretation in future reports",
    ),
    (
        "finance",
        "several reimbursements lacked readable receipts",
        "multiple expense claims had illegible supporting documents",
        "asked claimants for replacements before approval",
        "obtained clear copies before authorizing payment",
        "supported claims were paid without exceptions",
        "documented expenses were reimbursed through the normal process",
        "check document quality at submission",
        "validate receipt readability when a claim arrives",
    ),
    (
        "finance",
        "the forecast used an expired supplier quote",
        "the budget projection relied on an out-of-date vendor price",
        "obtained a current estimate and recalculated the total",
        "requested fresh pricing and recomputed the forecast",
        "the revised budget stayed within its ceiling",
        "the updated projection remained under the spending limit",
        "record quotation expiry dates",
        "track when every supplier estimate becomes invalid",
    ),
    (
        "software",
        "a release increased error rates for mobile users",
        "the deployment caused more failures on mobile traffic",
        "disabled the feature flag and restored the prior path",
        "turned off the new feature and returned requests to the earlier code path",
        "error rates returned to baseline",
        "mobile failures fell back to their normal level",
        "add mobile traffic to the pre-release check",
        "include mobile requests in release validation",
    ),
    (
        "software",
        "a nightly job processed one batch twice",
        "the overnight pipeline duplicated a source batch",
        "removed the duplicate trigger and reran the affected validation",
        "deleted the extra schedule event and repeated validation for the batch",
        "the corrected output contained one record per source",
        "the repaired result had no duplicated source records",
        "alert on overlapping job starts",
        "notify operators when scheduled runs overlap",
    ),
    (
        "community",
        "visitors could not find the accessible entrance",
        "attendees had no clear route to the step-free doorway",
        "added route details to the notice and placed signs outside",
        "published accessible directions and installed exterior wayfinding",
        "all registered visitors reached the venue independently",
        "every registered attendee entered without navigation assistance",
        "include an accessibility route in every event brief",
        "add step-free directions to all future event information",
    ),
    (
        "community",
        "volunteers arrived at different check-in doors",
        "the shift team split across multiple entrances",
        "named one entrance in the shift message and roster",
        "put a single arrival point in both the reminder and schedule",
        "the next handoff began without delays",
        "the following shift change started on time",
        "confirm the arrival point in every reminder",
        "state one check-in location in each future message",
    ),
    (
        "communications",
        "an outage notice did not identify the affected service",
        "the incident message omitted which product was unavailable",
        "published a correction naming the service and alternative",
        "issued a revised notice with the product name and workaround",
        "support calls about the notice decreased",
        "fewer readers contacted support for clarification",
        "require impact and workaround fields before release",
        "make service impact and alternatives mandatory in later notices",
    ),
    (
        "communications",
        "a newsletter repeated an outdated event date",
        "the mailing carried an event date that had already changed",
        "corrected the web and email copies and noted the change",
        "updated both channels and clearly marked the revision",
        "readers received one consistent date",
        "all published versions showed the same schedule",
        "verify linked dates during final review",
        "cross-check every referenced date before publication",
    ),
)


SUMMARY_CONTEXTS = (
    ("during the morning handoff", "during a change of morning staff"),
    ("just before the public opening", "before visitors were admitted"),
    ("after an unexpected schedule change", "following a late timetable revision"),
    ("while the primary owner was away", "in the usual owner's absence"),
    ("during the busiest service period", "at the point of highest demand"),
    ("after a previous fix failed", "following an unsuccessful earlier remedy"),
    ("while another team depended on the result", "with a downstream team waiting"),
    ("near the end of the reporting cycle", "as the reporting period closed"),
)


SUMMARY_CONSTRAINTS = (
    ("A backup service had to remain available.", "the response preserved a working fallback"),
    ("A second owner needed a clear audit trail.", "the handoff retained traceable evidence"),
    ("The change had to remain reversible that day.", "the team kept a same-day rollback path"),
    ("No additional budget was available.", "the work stayed within existing resources"),
)


__all__ = ("SUMMARY_CASES", "SUMMARY_CONSTRAINTS", "SUMMARY_CONTEXTS")
