from __future__ import annotations

_PRACTICAL_CARDS = {
    "public_transit": (
        "the transit operator",
        "a provisional departure",
        "reserving the journey",
        (
            "travel day, departure time, fare, and accessibility status",
            "the service date, departure schedule, ticket price, and accessible-travel arrangements",
            "when the journey leaves, what it costs, and which accessibility support is confirmed",
            "departure timing together with the quoted fare and access provisions",
        ),
        "the existing ticket",
    ),
    "healthcare_admin": (
        "the clinic",
        "a provisional appointment",
        "confirming the appointment",
        (
            "appointment day, arrival time, fee, and preparation instructions",
            "the scheduled date, check-in time, expected charge, and required preparation",
            "when to attend, when to arrive, what is payable, and how to prepare",
            "visit timing together with cost information and pre-appointment requirements",
        ),
        "the current appointment record",
    ),
    "air_travel": (
        "the airline",
        "a refundable itinerary",
        "booking the flight",
        (
            "travel day, departure time, fare, and refund conditions",
            "the flight date, scheduled departure, total price, and refund policy",
            "when the flight leaves, what the itinerary costs, and when a refund remains available",
            "departure details together with the quoted fare and reimbursement terms",
        ),
        "the existing itinerary",
    ),
    "retail_returns": (
        "the retailer",
        "a reversible return appointment",
        "sending the item back",
        (
            "return deadline, drop-off time, fee, and refund method",
            "the last return date, handoff window, applicable charge, and reimbursement route",
            "when the item must be returned, where timing matters, what it costs, and how repayment arrives",
            "return timing together with the quoted fee and refund channel",
        ),
        "the item and proof of purchase",
    ),
    "account_access": (
        "official account support",
        "a reversible identity-check session",
        "starting account recovery",
        (
            "review day, support time, identity-check method, and any fee",
            "when support will review the case, how identity will be checked, and whether a fee applies",
            "the scheduled review, available support window, verification process, and cost",
            "review timing together with the required identity evidence and any charge",
        ),
        "the current credentials and security settings",
    ),
    "event_registration": (
        "the event organizer",
        "a provisional registration slot",
        "submitting the registration",
        (
            "event day, arrival time, fee, and cancellation terms",
            "the scheduled date, check-in window, total cost, and cancellation policy",
            "when attendance begins, when to arrive, what is payable, and whether the booking can be cancelled",
            "registration timing together with the quoted charge and withdrawal conditions",
        ),
        "the current registration state",
    ),
    "subscriptions": (
        "the subscription provider",
        "a reversible plan change",
        "changing the subscription",
        (
            "effective day, plan, price, and renewal terms",
            "when the change begins, which plan applies, its cost, and the next renewal conditions",
            "the activation date, selected tier, quoted price, and recurring-billing rules",
            "plan-change timing together with the new charge and renewal policy",
        ),
        "the current plan",
    ),
    "course_enrolment": (
        "the course administrator",
        "a provisional class place",
        "enrolling in the course",
        (
            "start day, session time, fee, and prerequisites",
            "the course start date, class schedule, total charge, and entry requirements",
            "when teaching begins, when sessions meet, what enrolment costs, and what must be completed first",
            "course timing together with the quoted fee and required prior qualifications",
        ),
        "the current enrolment state",
    ),
    "banking_admin": (
        "the bank through its official channel",
        "a provisional service appointment",
        "authorizing the account request",
        (
            "service day, appointment time, fee, and required documents",
            "the banking date, reserved time, applicable charge, and documents to bring",
            "when the service occurs, what it costs, and which records the bank requires",
            "appointment timing together with fee information and the evidence needed",
        ),
        "the current account instructions",
    ),
    "appointments": (
        "the service desk",
        "a provisional appointment",
        "confirming the appointment",
        (
            "appointment day, time, price, and cancellation terms",
            "the reserved date and time, quoted cost, and cancellation policy",
            "when the appointment occurs, what it costs, and how cancellation is handled",
            "booking timing together with the total price and withdrawal conditions",
        ),
        "the current appointment",
    ),
    "home_repair": (
        "the repair provider",
        "a provisional visit",
        "authorizing the repair visit",
        (
            "visit day, arrival window, quoted price, and work scope",
            "the scheduled visit, expected arrival range, price quote, and authorized repair work",
            "when the provider will arrive, what the visit costs, and which work is included",
            "appointment timing together with the agreed price and exact repair boundary",
        ),
        "the property and existing work order",
    ),
    "parcel_delivery": (
        "the carrier",
        "a reversible redelivery slot",
        "requesting redelivery",
        (
            "delivery day, time window, fee, and destination",
            "the redelivery date, expected arrival range, applicable charge, and confirmed address",
            "when the parcel should arrive, where it is going, and whether redelivery costs anything",
            "delivery timing together with the quoted fee and destination details",
        ),
        "the current delivery instruction",
    ),
}


def practical_cards(
    domain: str,
) -> tuple[str, str, str, str | tuple[str, ...], str]:
    """Return localized semantic cells for one practical-action domain."""

    return _PRACTICAL_CARDS[domain]


def practical_answer_cards(
    *,
    provider: str,
    code: str,
    action: str,
    day: int,
    confirmation: str,
    protected_state: str,
) -> tuple[tuple[str, ...], ...]:
    """Build the linked action, owner, timing, and confirmation reservoirs."""

    return (
        (
            f"Next step: ask {provider} to reconcile references {code}-A and {code}-B before {action}.",
            f"Next step: place references {code}-A and {code}-B before {provider} for reconciliation.",
            f"Next step: pause {action} and request one corrected record covering {code}-A and {code}-B.",
            f"Next step: have {provider} confirm which of {code}-A or {code}-B is current.",
            f"Next step: send {code}-A and {code}-B to {provider} and request one authoritative version before {action}.",
            f"Next step: keep {action} on hold while {provider} resolves the conflict between {code}-A and {code}-B.",
            f"Next step: ask {provider} for written reconciliation of {code}-A against {code}-B.",
            f"Next step: present both {code}-A and {code}-B to {provider} before making any commitment.",
            f"Next step: request a single verified record from {provider} covering references {code}-A and {code}-B.",
            f"Next step: preserve the current state and have {provider} compare {code}-A with {code}-B.",
            f"Next step: open a reconciliation request with {provider} for {code}-A and {code}-B before {action}.",
            f"Next step: require {provider} to identify the governing record between {code}-A and {code}-B.",
            f"Next step: defer {action} until {provider} issues a correction for the two references.",
            f"Next step: give {provider} both conflicting entries and ask for a confirmed replacement record.",
            f"Next step: keep the provisional option unchanged while {provider} reconciles {code}-A and {code}-B.",
            f"Next step: obtain one source from {provider} that resolves the discrepancy between {code}-A and {code}-B.",
            f"Next step: make reconciliation of {code}-A and {code}-B the prerequisite for {action}.",
            f"Next step: ask {provider} to correct or supersede the conflicting references in writing.",
            f"Next step: submit the pair {code}-A and {code}-B for verification by {provider}.",
            f"Next step: stop before {action} and request {provider}'s authoritative comparison of both records.",
            f"Next step: have {provider} document which reference controls and why the other is outdated.",
            f"Next step: seek a reconciled version of {code}-A and {code}-B through {provider}'s official channel.",
            f"Next step: resolve the two-record conflict with {provider} while every commitment remains reversible.",
            f"Next step: obtain {provider}'s signed-off comparison of {code}-A and {code}-B before resuming {action}.",
            f"Next step: route both {code}-A and {code}-B through {provider}'s official review before continuing with {action}.",
            f"Next step: preserve the conflicting pair and ask {provider} to replace it with one verified instruction.",
            f"Next step: suspend {action}, attach the two records to a provider query, and await an authoritative answer.",
            f"Next step: require a documented ruling from {provider} on which of {code}-A and {code}-B controls.",
            f"Next step: keep the current option provisional while {provider} validates the dates and terms in both references.",
            f"Next step: open an official discrepancy case so {provider} can reconcile the source behind {code}-A with {code}-B.",
            f"Next step: make no commitment until {provider} returns a single corrected version covering both entries.",
            f"Next step: request that {provider} compare, supersede, and document the disputed records before {action} resumes.",
        ),
        (
            f"Owner: the requester contacts {provider}; the provider owns the corrected record.",
            f"Owner: {provider} returns the correction once the requester opens the query.",
            f"Owner: once the requester supplies both references, {provider} resolves the discrepancy.",
            f"Owner: the requester submits {code}-A and {code}-B, while {provider} supplies the authoritative reconciliation.",
            f"Owner: {provider} is responsible for deciding which record governs after the requester presents both entries.",
            f"Owner: the requester initiates the review; {provider} owns verification and correction of the records.",
            f"Owner: {provider} must issue the corrected source after receiving the conflicting references.",
            f"Owner: the requester preserves both entries and {provider} documents the resolution.",
            f"Owner: reconciliation belongs to {provider}; the requester only supplies the evidence and keeps the action paused.",
            f"Owner: the requester opens the official case, then {provider} confirms the current record.",
            f"Owner: {provider} compares {code}-A with {code}-B and returns one verified answer to the requester.",
            f"Owner: the requester asks for review, but authority to correct the record remains with {provider}.",
            f"Owner: {provider} owns the written correction once both references are attached to the query.",
            f"Owner: the requester reports the conflict and {provider} closes it with an authoritative record.",
            f"Owner: verification is performed by {provider} after the requester identifies the two conflicting entries.",
            f"Owner: the requester keeps the current state unchanged while {provider} resolves the source conflict.",
            f"Owner: {provider} supplies the governing version; the requester is responsible for initiating the request.",
            f"Owner: the requester provides the comparison material and {provider} owns the final record decision.",
            f"Owner: {provider} handles reconciliation through its official channel once the pair is submitted.",
            f"Owner: correction remains {provider}'s responsibility, with the requester responsible for preserving both references.",
            f"Owner: the requester requests one confirmed source and {provider} returns the documented resolution.",
            f"Owner: {provider} determines the valid entry while the requester avoids acting on either disputed version.",
            f"Owner: the requester raises the discrepancy; {provider} verifies, corrects, and records the outcome.",
            f"Owner: {provider} owns the authoritative response after the requester supplies {code}-A and {code}-B.",
            f"Owner: the requester files the discrepancy, and {provider} decides which dated source remains valid.",
            f"Owner: {provider} performs the record comparison; the requester keeps both references available for review.",
            f"Owner: initiating the case belongs to the requester, while correcting its official source belongs to {provider}.",
            f"Owner: after receiving {code}-A and {code}-B, {provider} records the controlling version and reports it back.",
            f"Owner: the requester maintains the reversible hold; {provider} supplies and owns the final reconciliation.",
            f"Owner: {provider} has authority over the corrected entry, with the requester responsible only for presenting the conflict.",
            f"Owner: the official comparison is {provider}'s task once the requester has opened a documented query.",
            f"Owner: the requester preserves the evidence and {provider} determines the authoritative state.",
        ),
        (
            f"Timing: complete the check before day {day}.",
            f"Timing: obtain the corrected record before day {day}.",
            f"Timing: resolve the discrepancy before the day {day} cutoff.",
            f"Timing: finish reconciliation no later than day {day}.",
            f"Timing: secure the provider's correction no later than day {day}.",
            f"Timing: keep commitment paused until the records agree, with day {day} as the deadline.",
            f"Timing: close the reference check ahead of day {day}.",
            f"Timing: require the authoritative record by the end of day {day}.",
            f"Timing: complete provider verification prior to day {day}.",
            f"Timing: use day {day} as the latest date for resolving both references.",
            f"Timing: reconcile the conflicting entries before the day {day} cutoff and before commitment.",
            f"Timing: obtain one confirmed version before day {day} begins.",
            f"Timing: keep the action on hold and settle the reference conflict before day {day} ends.",
            f"Timing: ask for the corrected source now and require it no later than day {day}.",
            f"Timing: use the period ending on day {day} to verify which record governs.",
            f"Timing: complete the comparison and receive provider confirmation no later than day {day}.",
            f"Timing: do not pass day {day} without either a reconciled record or a continued hold.",
            f"Timing: resolve both dated entries before the close of day {day}.",
            f"Timing: make day {day} the deadline for one authoritative response from {provider}.",
            f"Timing: finish the record check ahead of any commitment and no later than day {day}.",
            f"Timing: obtain written reconciliation during the window that ends on day {day}.",
            f"Timing: leave the provisional option unchanged until verification arrives, using day {day} as the deadline.",
            f"Timing: require agreement between the references on or before day {day}.",
            f"Timing: conclude the provider query before day {day} closes, keeping the current state until then.",
            f"Timing: before day {day} ends, obtain either a resolved record or confirmation that the hold continues.",
            f"Timing: give {provider} until day {day} to issue one documented and authoritative version.",
            f"Timing: keep all action reversible while the comparison is completed no later than day {day}.",
            f"Timing: settle which entry controls during the verification period that closes on day {day}.",
            f"Timing: require a written result no later than day {day} before resuming any commitment.",
            f"Timing: start the source review immediately and retain the hold through its day {day} deadline.",
            f"Timing: the record conflict must be closed, or explicitly remain on hold, at the day {day} checkpoint.",
            f"Timing: receive the provider's comparison ahead of any action scheduled after day {day}.",
        ),
        (
            f"Confirm the {confirmation} in writing before commitment; otherwise preserve {protected_state}.",
            f"Proceed only after the {confirmation} is verified; if not, retain {protected_state}.",
            f"Do not continue with {action} until the {confirmation} is recorded; leave {protected_state} unchanged meanwhile.",
            f"Keep {protected_state} in place unless written evidence confirms the {confirmation}.",
            f"Require documented confirmation of the {confirmation} before replacing {protected_state}.",
            f"If the {confirmation} remains unresolved, stop and preserve {protected_state} rather than proceeding.",
            f"Treat the action as provisional until the {confirmation} appears in the authoritative record.",
            f"Advance only when {provider} verifies the {confirmation}; otherwise keep {protected_state}.",
            f"Use written proof of the {confirmation} as the release condition for {action}.",
            f"Leave {protected_state} untouched until the corrected source establishes the {confirmation}.",
            f"Without a verified {confirmation}, maintain the hold and retain {protected_state}.",
            f"Make the documented {confirmation} the final prerequisite before commitment.",
            f"Preserve {protected_state} if {provider} cannot confirm the {confirmation} in writing.",
            f"The reversible default is {protected_state} until the {confirmation} is independently recorded.",
            f"Release the hold only after the authoritative response verifies the {confirmation}.",
            f"If the corrected record does not establish the {confirmation}, do not continue with {action}.",
            f"Keep the current arrangement reversible until written confirmation resolves the {confirmation}.",
            f"Use verification of the {confirmation}, not assumption, as the condition for proceeding.",
            f"Retain {protected_state} whenever the provider's response leaves the {confirmation} uncertain.",
            f"Commit only after the reconciled record explicitly supports the {confirmation}.",
            f"Until {provider} documents the {confirmation}, the safe state remains {protected_state}.",
            f"A missing confirmation keeps {action} paused and {protected_state} preserved.",
            f"Document the {confirmation} first; absent that evidence, continue to protect {protected_state}.",
            f"Let the authoritative record decide whether the {confirmation} is established before any irreversible step.",
            f"Keep {action} paused until a verified source records the {confirmation}.",
            f"Proceed from {protected_state} only when the corrected entry documents the {confirmation}.",
            f"Wait for {provider} to establish the {confirmation} before changing {protected_state}.",
            f"Use the reconciled source—not an inference—to confirm the {confirmation} before moving ahead.",
            f"The next commitment depends on written evidence of the {confirmation}; until then, retain {protected_state}.",
            f"Do not replace {protected_state} unless the authoritative comparison settles the {confirmation}.",
            f"Require a verified record of the {confirmation} before resuming {action}.",
            f"Hold the current state until {provider}'s corrected record supports the {confirmation}.",
        ),
    )
