from __future__ import annotations

from typing import Any


def _variants(*sentences: str) -> tuple[str, ...]:
    if len(sentences) < 8:
        raise ValueError("casual semantic cells require at least eight surfaces")
    return tuple(sentences)


CASUAL_INTENT_CARDS: tuple[dict[str, Any], ...] = (
    {
        "intent_id": "intent:share_small_pleasure",
        "user_opening": _variants(
            "I mostly wanted to share why this small thing pleased me.",
            "There is no problem to solve; I simply enjoyed noticing it.",
            "I felt like telling someone about this little pleasure.",
            "The moment was modest, but it brightened my day.",
            "I am bringing it up because the enjoyment surprised me.",
            "It seemed too pleasant to let pass without mentioning it.",
            "I do not need advice here; sharing it is enough.",
            "This is really just a small good thing from my day.",
        ),
        "assistant_entry": _variants(
            "Small pleasures can be worth giving a little attention.",
            "The enjoyment comes through without needing to become a problem.",
            "It is nice to stay with something simply because it felt good.",
            "A modest bright spot can carry a surprising amount of warmth.",
            "That sounds like the kind of detail worth sharing for its own sake.",
            "The pleasure itself seems to be the important part here.",
            "Nothing about that needs fixing before it can be appreciated.",
            "There is room in a conversation for an uncomplicated good moment.",
        ),
        "closing_focus": (
            "the simple pleasure",
            "the bright moment",
            "the uncomplicated enjoyment",
            "the small good thing",
        ),
    },
    {
        "intent_id": "intent:understand_preference",
        "user_opening": _variants(
            "I am trying to understand why this suits me so well.",
            "Part of my interest is figuring out what makes it work for me.",
            "I know I like it, although the reason is still taking shape.",
            "I have been wondering why I prefer this version of the experience.",
            "The preference is clear to me even if its cause is not yet clear.",
            "I want to look more closely at what makes this feel right.",
            "Something about it fits me better than I expected.",
            "I am curious about the reason this particular form appeals to me.",
        ),
        "assistant_entry": _variants(
            "A preference often becomes clearer once its concrete parts are visible.",
            "The reason may be hiding in one ordinary feature of the experience.",
            "Knowing that it fits is already a useful place to begin.",
            "The appeal may come from several small details working together.",
            "Looking at the experience closely could make the preference easier to name.",
            "A strong preference does not always arrive with an immediate explanation.",
            "The fit may become clearer through the example rather than an abstract reason.",
            "There is probably a specific quality behind that sense of rightness.",
        ),
        "closing_focus": (
            "the emerging preference",
            "the sense of fit",
            "the source of the appeal",
            "the reason it feels right",
        ),
    },
    {
        "intent_id": "intent:compare_with_past",
        "user_opening": _variants(
            "It feels different from how I would have experienced it before.",
            "I keep comparing this reaction with the one I used to have.",
            "The change from my earlier response is part of what interests me.",
            "A while ago I probably would not have noticed this in the same way.",
            "My reaction has shifted, and I am curious about the difference.",
            "The contrast with the past makes the present moment stand out.",
            "I am noticing how much my response has changed over time.",
            "This would have felt quite different to me a few years ago.",
        ),
        "assistant_entry": _variants(
            "A changed reaction can reveal as much as the experience itself.",
            "The contrast gives you two versions of the same subject to compare.",
            "Sometimes the clearest change appears in what now catches our attention.",
            "That difference over time sounds central to why the moment stood out.",
            "Comparing past and present may show what has quietly shifted.",
            "The new response could make an old experience feel newly available.",
            "A familiar subject can change when the person meeting it has changed.",
            "The earlier reaction provides a useful background for the current one.",
        ),
        "closing_focus": (
            "the change over time",
            "the newer response",
            "the contrast with the past",
            "the shifted perspective",
        ),
    },
    {
        "intent_id": "intent:name_feeling",
        "user_opening": _variants(
            "I can describe the moment more easily than I can name the feeling.",
            "There is a particular mood here that I have not quite identified.",
            "I know how it felt, but I am still looking for the right word.",
            "The feeling is distinct even though its name keeps escaping me.",
            "I want to understand the mood without forcing it into the wrong label.",
            "Something emotional is clear in the experience, but not yet precise.",
            "I am curious whether the feeling is calm, excitement, or something between them.",
            "The details are vivid while the emotion remains difficult to summarize.",
        ),
        "assistant_entry": _variants(
            "The shape of a feeling can be clear before its name is.",
            "The details may point toward the mood without reducing it to one word.",
            "It makes sense to describe the experience before choosing a label.",
            "Some feelings are better approached through texture than definition.",
            "The right word may matter less than noticing what the feeling does.",
            "A mood can stay precise even when it falls between familiar categories.",
            "There is no need to settle the label before exploring the experience.",
            "The emotion may become clearer as its most vivid detail comes forward.",
        ),
        "closing_focus": (
            "the hard-to-name feeling",
            "the mood of the moment",
            "the emotional texture",
            "the feeling taking shape",
        ),
    },
    {
        "intent_id": "intent:follow_one_detail",
        "user_opening": _variants(
            "One detail keeps pulling my attention back to the experience.",
            "I am less interested in the whole story than in one small part of it.",
            "A particular feature has stayed much clearer than everything around it.",
            "The experience seems to turn on a single detail for me.",
            "I keep returning to one part without entirely knowing why.",
            "Most of the moment has faded, but one feature remains vivid.",
            "There is one small element I would like to follow more closely.",
            "The detail may be ordinary, yet it has become the center of the memory.",
        ),
        "assistant_entry": _variants(
            "A persistent detail often carries the meaning of a larger moment.",
            "Following the clearest feature may be more revealing than retelling everything.",
            "The part that remains vivid probably earned that attention somehow.",
            "A small element can become the doorway back into the whole experience.",
            "The detail seems worth examining without assuming what it means.",
            "What stayed may tell us more than what happened first.",
            "The narrow focus gives the conversation somewhere concrete to begin.",
            "One well-observed feature can hold a surprisingly complete story.",
        ),
        "closing_focus": (
            "the persistent detail",
            "the feature that stayed",
            "the small focal point",
            "the detail at the center",
        ),
    },
    {
        "intent_id": "intent:imagine_next_time",
        "user_opening": _variants(
            "I have also been wondering how this might feel the next time.",
            "Part of me is already imagining a future version of the experience.",
            "I would like to know what I might keep or change when it happens again.",
            "The moment has made me curious about returning to it deliberately.",
            "I am thinking ahead without wanting to plan every detail.",
            "There may be another version of this worth trying later.",
            "I want to carry something from this experience into the next one.",
            "The possibility of repeating it is now part of the appeal.",
        ),
        "assistant_entry": _variants(
            "Looking ahead can clarify which part of the experience matters most.",
            "A future version does not have to reproduce every detail to preserve the appeal.",
            "The thought of returning suggests that something here felt worth keeping.",
            "Imagining next time can separate the essential part from the accidental one.",
            "There is room to repeat the experience without turning it into a rigid plan.",
            "The useful question may be what deserves to travel into the next attempt.",
            "Anticipation can reveal which feature you most want to meet again.",
            "A loose future possibility seems to fit the spirit of what you described.",
        ),
        "closing_focus": (
            "the possible return",
            "the next version",
            "the wish to revisit it",
            "the future possibility",
        ),
    },
    {
        "intent_id": "intent:invite_perspective",
        "user_opening": _variants(
            "I am curious how this sounds from someone else's point of view.",
            "It would be interesting to hear what another person notices in it.",
            "I know my own reaction and want to see the experience from outside.",
            "Part of why I am sharing this is to invite another perspective.",
            "I wonder whether the same detail would stand out to someone else.",
            "I would like a different angle without turning the exchange into advice.",
            "My view is clear enough; I am curious what it leaves unseen.",
            "I want to place my reaction beside another reading of the moment.",
        ),
        "assistant_entry": _variants(
            "Another perspective can add an angle without replacing your own.",
            "The way you tell it already suggests several possible points of emphasis.",
            "A view from outside may notice a pattern that feels ordinary from within.",
            "It is possible to offer another reading while keeping your reaction central.",
            "The detail could look different depending on where the attention begins.",
            "A second angle may expand the moment rather than explain it away.",
            "The experience leaves room for more than one honest interpretation.",
            "Hearing another view can make the contours of your own response clearer.",
        ),
        "closing_focus": (
            "the second perspective",
            "the view from outside",
            "the additional angle",
            "the shared interpretation",
        ),
    },
    {
        "intent_id": "intent:talk_without_goal",
        "user_opening": _variants(
            "There is no larger goal behind this; I simply felt like talking.",
            "I am not trying to reach a conclusion about it.",
            "This is one of those thoughts that seems better shared than solved.",
            "I do not have a question prepared, only an experience to mention.",
            "The conversation itself is probably all I want from the thought.",
            "I am happy to let this remain an ordinary piece of conversation.",
            "Nothing urgent follows from it; it was just on my mind.",
            "I wanted to say it aloud without making it into a project.",
        ),
        "assistant_entry": _variants(
            "A conversation does not need a problem before it can be worthwhile.",
            "We can stay with the thought without steering it toward a conclusion.",
            "An ordinary observation is enough material for a real exchange.",
            "There is no need to turn what you shared into a task.",
            "The experience can remain open while we talk about what made it noticeable.",
            "Simply giving the thought some company seems appropriate here.",
            "We can follow the interesting part without deciding where it must lead.",
            "A little curiosity is enough structure for this kind of conversation.",
        ),
        "closing_focus": (
            "the unforced conversation",
            "the thought shared aloud",
            "the open exchange",
            "the ordinary conversation",
        ),
    },
)


CASUAL_ARC_CARDS: tuple[dict[str, Any], ...] = (
    {
        "arc_id": "arc:sensory_detail",
        "user_follow_up": _variants(
            "The sensory part is what returns first when I remember it.",
            "A sound, texture, color, or smell made the experience unusually vivid.",
            "What stayed was less an idea than a physical impression.",
            "The moment became memorable through something I could directly sense.",
            "I can recall the atmosphere more easily than the exact sequence.",
            "One sensory detail gave the whole experience its character.",
            "The clearest part of the memory is almost physical.",
            "Its texture and atmosphere mattered more than I expected.",
        ),
        "user_shift": _variants(
            "Thinking about it now, the atmosphere may have mattered most.",
            "I probably understood the moment through my senses before my thoughts.",
            "The physical detail seems to hold the rest of the memory together.",
            "I would notice the atmosphere first if it happened again.",
            "That sensory impression may explain why it stayed vivid.",
            "The experience feels clearer when I return to its texture.",
            "I had focused on the event, but the atmosphere was doing more work.",
            "The memory seems anchored in that direct impression.",
        ),
        "closing_lens": (
            "the sensory detail",
            "the remembered atmosphere",
            "the physical impression",
            "the texture of the moment",
        ),
    },
    {
        "arc_id": "arc:gentle_contrast",
        "user_follow_up": _variants(
            "A quiet contrast inside the experience is what made it interesting.",
            "Two parts that should have competed somehow worked together.",
            "The moment held a difference that felt balanced rather than jarring.",
            "I noticed it because one element set off another.",
            "The appeal came partly from two unlike qualities meeting.",
            "There was a small tension in it, but not an unpleasant one.",
            "One feature made the other easier to notice by contrast.",
            "The difference between the parts gave the experience its shape.",
        ),
        "user_shift": _variants(
            "The contrast may be more important than either side alone.",
            "I think the balance between the two parts is what I liked.",
            "Without that difference, the experience might have felt flatter.",
            "The two qualities seem to define each other.",
            "I had noticed both parts but not how much their contrast mattered.",
            "The tension now feels like a feature rather than a complication.",
            "I would probably miss the difference if everything became uniform.",
            "Seeing the parts together makes the appeal easier to understand.",
        ),
        "closing_lens": (
            "the gentle contrast",
            "the balance between differences",
            "the paired qualities",
            "the tension between the parts",
        ),
    },
    {
        "arc_id": "arc:memory_connection",
        "user_follow_up": _variants(
            "It also connected with an older memory I had not expected to revisit.",
            "The present moment brought back something related from much earlier.",
            "Part of its force came from the memory it quietly reopened.",
            "I recognized a feeling from another time inside this experience.",
            "An old association appeared without taking over the new moment.",
            "The detail seemed familiar before I understood what it recalled.",
            "Something in it reached back to a memory I rarely think about.",
            "The experience gained another layer when the earlier memory surfaced.",
        ),
        "user_shift": _variants(
            "The memory explains part of my reaction, though not all of it.",
            "I can now see the older association beside the present experience.",
            "The connection makes the moment richer without making it only nostalgic.",
            "I had underestimated how much the earlier memory shaped my attention.",
            "The past seems present as a background rather than the main subject.",
            "That association may be why the detail felt immediately familiar.",
            "The new moment still stands on its own, but the memory adds depth.",
            "Recognizing the connection changes how I understand my response.",
        ),
        "closing_lens": (
            "the older memory",
            "the quiet association",
            "the link across time",
            "the remembered connection",
        ),
    },
    {
        "arc_id": "arc:habit_emerges",
        "user_follow_up": _variants(
            "I can imagine this becoming a small habit without much effort.",
            "The experience already has the shape of something I might repeat.",
            "Its simplicity makes it feel easy to return to regularly.",
            "Nothing about it requires ideal conditions, which makes repetition possible.",
            "A routine could grow from this without needing a strict schedule.",
            "The appealing part may be how naturally it fits into ordinary life.",
            "I noticed that repeating it would not demand much preparation.",
            "It feels sustainable precisely because the action is modest.",
        ),
        "user_shift": _variants(
            "I would rather protect the easy version than make the habit ambitious.",
            "The repetition matters less than keeping the experience light.",
            "A loose routine seems more suitable than a formal commitment.",
            "I can see a place for it in daily life without forcing it.",
            "The small scale may be what allows the habit to last.",
            "I would keep the conditions simple if I returned to it regularly.",
            "Its ordinary fit now seems as important as the experience itself.",
            "The habit could remain flexible and still feel meaningful.",
        ),
        "closing_lens": (
            "the emerging habit",
            "the easy repetition",
            "the sustainable routine",
            "the place in daily life",
        ),
    },
    {
        "arc_id": "arc:unexpected_turn",
        "user_follow_up": _variants(
            "The part that surprised me was not the one I expected to matter.",
            "My attention moved somewhere different from where it began.",
            "A minor feature ended up changing the whole experience.",
            "The moment became interesting only after an unplanned turn.",
            "What I remember most was almost incidental at first.",
            "The experience resisted the story I thought it would have.",
            "Something peripheral unexpectedly became the central part.",
            "The strongest impression arrived from a direction I had not anticipated.",
        ),
        "user_shift": _variants(
            "The surprise may be why the experience still feels alive.",
            "I like that the important part could not have been planned.",
            "The change in attention seems more memorable than the original expectation.",
            "I would leave room for the same kind of surprise next time.",
            "The unplanned turn now feels essential to the story.",
            "I had mistaken the expected part for the meaningful one.",
            "The experience became mine when it stopped following the anticipated path.",
            "That shift explains why the moment did not feel routine.",
        ),
        "closing_lens": (
            "the unexpected turn",
            "the change in attention",
            "the unplanned discovery",
            "the surprising center",
        ),
    },
    {
        "arc_id": "arc:social_connection",
        "user_follow_up": _variants(
            "Another person's presence changed the tone without dominating it.",
            "The experience became more noticeable because it was partly shared.",
            "A small exchange with someone else gave the moment extra warmth.",
            "The social part was brief, but it changed how I remember everything around it.",
            "Someone else's reaction helped me notice a feature I might have missed.",
            "The moment felt personal while still belonging to more than one person.",
            "A little mutual recognition made the ordinary setting feel different.",
            "The connection came through a small gesture rather than a long conversation.",
        ),
        "user_shift": _variants(
            "The shared part mattered even though neither of us made much of it.",
            "I think the quiet recognition was enough to change the moment.",
            "The other person added something without needing to explain it.",
            "It may have felt memorable because the attention was briefly mutual.",
            "The connection now seems woven into the rest of the experience.",
            "I would not separate the setting from the person who shared it.",
            "That small social element gave the moment more life.",
            "The exchange was light, but its effect was not trivial.",
        ),
        "closing_lens": (
            "the shared moment",
            "the quiet connection",
            "the mutual recognition",
            "the social warmth",
        ),
    },
    {
        "arc_id": "arc:future_anticipation",
        "user_follow_up": _variants(
            "Part of the pleasure now comes from looking forward to it happening again.",
            "The experience has created a small point of anticipation.",
            "I find myself imagining the next occasion without trying to control it.",
            "Knowing it may return has changed how I think about the present moment.",
            "The possibility of another time adds energy to the memory.",
            "I am already curious about what might be different on a future occasion.",
            "The next version feels inviting precisely because it is not guaranteed.",
            "Anticipation has become a quiet continuation of the experience.",
        ),
        "user_shift": _variants(
            "I want to keep the anticipation without building up a rigid expectation.",
            "The future possibility is pleasant enough without needing a plan.",
            "I would rather remain curious than decide exactly how it should recur.",
            "Looking forward now feels like part of what the experience gave me.",
            "The next occasion can be different and still preserve the appeal.",
            "I think the openness of the future matters as much as repetition.",
            "The anticipation feels light rather than demanding.",
            "I can enjoy the possibility without asking it to repeat the past exactly.",
        ),
        "closing_lens": (
            "the light anticipation",
            "the open future",
            "the possibility of returning",
            "the next occasion",
        ),
    },
    {
        "arc_id": "arc:reconsideration",
        "user_follow_up": _variants(
            "The experience made me reconsider an assumption I had carried into it.",
            "One part did not fit my earlier view, and that was useful.",
            "I came away less certain of an old judgment than when I began.",
            "The detail opened a possibility I had previously dismissed.",
            "Something ordinary challenged the way I had been framing the subject.",
            "My first interpretation now seems narrower than the experience itself.",
            "The moment did not prove me wrong so much as make my view less rigid.",
            "A familiar assumption loosened when I noticed the concrete example.",
        ),
        "user_shift": _variants(
            "I do not need a replacement conclusion yet; the added possibility is enough.",
            "My view feels broader now without becoming completely different.",
            "The assumption may still contain some truth, just not the whole story.",
            "I am more willing to leave the question open after this experience.",
            "The change is subtle, but my earlier judgment no longer feels complete.",
            "I can hold the old view more lightly now.",
            "The example gave me a reason to remain curious instead of certain.",
            "Reconsidering it feels more honest than rushing toward a new rule.",
        ),
        "closing_lens": (
            "the loosened assumption",
            "the broader view",
            "the reconsidered judgment",
            "the newly open possibility",
        ),
    },
    {
        "arc_id": "arc:open_ending",
        "user_follow_up": _variants(
            "I am comfortable with the fact that the thought does not fully resolve.",
            "The experience leaves a question behind, and I do not mind that.",
            "Part of what I like is that no neat conclusion closes it off.",
            "The moment feels complete even though its meaning remains open.",
            "I can stay curious without deciding exactly what to make of it.",
            "Nothing in the experience demands a final interpretation.",
            "The unresolved part gives me a reason to keep noticing.",
            "I would rather preserve the question than force an answer too early.",
        ),
        "user_shift": _variants(
            "Leaving it open now feels more accurate than summarizing it.",
            "The uncertainty is part of the interest rather than a defect.",
            "I think the conversation can end without the thought being finished.",
            "The question may continue quietly after this exchange.",
            "I am satisfied with a clearer observation instead of a conclusion.",
            "The experience can remain unfinished without feeling incomplete.",
            "Keeping some room around it seems faithful to what happened.",
            "I would like the thought to stay flexible for a while longer.",
        ),
        "closing_lens": (
            "the open question",
            "the unresolved meaning",
            "the room left around it",
            "the unfinished thought",
        ),
    },
)


CASUAL_SEMANTIC_CLOSINGS = (
    "It seems {intent[closing_focus]} became clearer through {arc[closing_lens]}.",
    "The conversation leaves {intent[closing_focus]} connected to {arc[closing_lens]}.",
    "What remains is {intent[closing_focus]}, seen through {arc[closing_lens]}.",
    "That brings {intent[closing_focus]} and {arc[closing_lens]} into the same picture.",
    "The exchange gives {intent[closing_focus]} a place beside {arc[closing_lens]}.",
    "For now, {intent[closing_focus]} can rest with {arc[closing_lens]}.",
    "The clearest thread joins {intent[closing_focus]} with {arc[closing_lens]}.",
    "This makes room for both {intent[closing_focus]} and {arc[closing_lens]}.",
    "The thought now holds {intent[closing_focus]} together with {arc[closing_lens]}.",
    "A natural stopping point is where {intent[closing_focus]} meets {arc[closing_lens]}.",
    "The lasting impression combines {intent[closing_focus]} with {arc[closing_lens]}.",
    "The conversation has traced {intent[closing_focus]} through {arc[closing_lens]}.",
    "Seen together, {intent[closing_focus]} draws meaning from {arc[closing_lens]}.",
    "One thread now connects {intent[closing_focus]} to {arc[closing_lens]}.",
    "At this point, {arc[closing_lens]} helps explain {intent[closing_focus]}.",
    "The exchange places {arc[closing_lens]} behind {intent[closing_focus]}.",
    "Both {intent[closing_focus]} and {arc[closing_lens]} remain visible at the end.",
    "A final connection links {intent[closing_focus]} with {arc[closing_lens]}.",
    "In the end, {arc[closing_lens]} gives shape to {intent[closing_focus]}.",
    "The strongest connection runs from {arc[closing_lens]} to {intent[closing_focus]}.",
    "Together, {arc[closing_lens]} and {intent[closing_focus]} complete the reflection.",
    "The pause leaves {arc[closing_lens]} alongside {intent[closing_focus]}.",
    "Now {intent[closing_focus]} carries something of {arc[closing_lens]}.",
    "The ending keeps {arc[closing_lens]} close to {intent[closing_focus]}.",
)


CASUAL_COMPACT_CLOSINGS = (
    "{topic[compact]} can stay {context[compact]}, joining {intent[closing_focus]} with {arc[closing_lens]}.",
    "{topic[compact]} remains {context[compact]}, with {arc[closing_lens]} beside {intent[closing_focus]}.",
    "For now, {topic[compact]} feels {context[compact]} through {intent[closing_focus]} and {arc[closing_lens]}.",
    "The thought about {topic[compact]} stays {context[compact]}: {intent[closing_focus]} meets {arc[closing_lens]}.",
    "Seen as {context[compact]}, {topic[compact]} links {intent[closing_focus]} to {arc[closing_lens]}.",
    "Viewing {topic[compact]} as {context[compact]} holds {arc[closing_lens]} near {intent[closing_focus]}.",
    "With {topic[compact]} kept {context[compact]}, {intent[closing_focus]} can rest beside {arc[closing_lens]}.",
    "Here, {arc[closing_lens]} makes {topic[compact]} feel {context[compact]} while preserving {intent[closing_focus]}.",
    "What remains of {topic[compact]} is {context[compact]}: {intent[closing_focus]} and {arc[closing_lens]}.",
    "This leaves {topic[compact]} {context[compact]}, connecting {arc[closing_lens]} with {intent[closing_focus]}.",
    "Around {topic[compact]}, {intent[closing_focus]} stays {context[compact]} alongside {arc[closing_lens]}.",
    "At this point, {topic[compact]} feels {context[compact]}, joining {intent[closing_focus]} and {arc[closing_lens]}.",
    "Let {topic[compact]} remain {context[compact]}, carrying {intent[closing_focus]} with {arc[closing_lens]}.",
    "As {context[compact]}, {topic[compact]} brings {arc[closing_lens]} into {intent[closing_focus]}.",
    "Both {intent[closing_focus]} and {arc[closing_lens]} keep {topic[compact]} {context[compact]}.",
    "Keeping {topic[compact]} {context[compact]} lets {arc[closing_lens]} accompany {intent[closing_focus]}.",
)


CASUAL_BALANCED_CLOSINGS = tuple(
    "{topic[closing]} {context[closing_clause]}; "
    + closing[:1].lower()
    + closing[1:]
    for closing in CASUAL_SEMANTIC_CLOSINGS
)


CASUAL_CONTEXT_CLOSINGS = (
    "{context[closing]}",
    "For this exchange, {context[closing_lower]}",
    "At least for now, {context[closing_lower]}",
    "In this conversation, {context[closing_lower]}",
    "A fitting boundary is that {context[closing_lower]}",
    "The present thought allows that {context[closing_lower]}",
    "One useful limit is that {context[closing_lower]}",
    "The exchange can rest here because {context[closing_lower]}",
    "Without forcing anything further, {context[closing_lower]}",
    "As the conversation pauses, {context[closing_lower]}",
    "The current perspective still leaves room because {context[closing_lower]}",
    "For the moment, it is enough that {context[closing_lower]}",
    "Nothing more is required here since {context[closing_lower]}",
    "The thought remains proportionate when {context[closing_lower]}",
    "A natural limit appears in the fact that {context[closing_lower]}",
    "The exchange stays open in this way: {context[closing_lower]}",
    "The conversation need not go further because {context[closing_lower]}",
    "This stopping point works while {context[closing_lower]}",
    "The reflection keeps its balance when {context[closing_lower]}",
    "The present ending respects the fact that {context[closing_lower]}",
    "A little openness remains, since {context[closing_lower]}",
    "The conversation can stay light because {context[closing_lower]}",
    "What has been said is sufficient while {context[closing_lower]}",
    "The final note remains flexible because {context[closing_lower]}",
)
