from __future__ import annotations


# These reservoirs contain authored paraphrases of recurring semantic facts.
# They are deliberately separate from the card model: a card decides *what* an
# example means, while this table prevents one valid meaning from forcing one
# memorized sentence. Every replacement keeps the same factual boundary.
REPETITION_LITERAL_RESERVOIRS: dict[
    str, tuple[tuple[str, tuple[str, ...], tuple[str, ...]], ...]
] = {
    "brainstorming_creativity": (
        (
            "brainstorm-avoid-risk",
            (
                "Avoid ideas that create unnecessary safety, privacy, or exclusion risks.",
            ),
            (
                "Discard any idea that introduces avoidable safety, privacy, or access risk.",
                "Do not retain proposals with needless privacy, safety, or exclusion concerns.",
                "Remove options that add preventable harm, privacy exposure, or exclusion.",
                "Screen out ideas whose risks to safety, privacy, or access are unnecessary.",
                "Keep only options that avoid needless safety, privacy, and inclusion problems.",
                "Reject concepts that create avoidable hazards, data exposure, or barriers to participation.",
                "Treat preventable safety, privacy, and accessibility risks as disqualifying.",
                "Exclude proposals that introduce needless harm, privacy loss, or participation barriers.",
                "Prefer alternatives without unnecessary hazards, privacy concerns, or exclusion effects.",
                "Set aside any option that adds preventable safety, confidentiality, or access risk.",
                "Filter out concepts with avoidable physical, privacy, or inclusion costs.",
                "Retain no idea whose safety, privacy, or participation risk lacks a clear need.",
            ),
        ),
        (
            "brainstorm-practical-result",
            ("Practical result: each retained option satisfies the stated criteria.",),
            (
                "Each remaining option meets the brief's stated requirements.",
                "The retained alternatives all satisfy the named criteria.",
                "Every option still under consideration fits the stated limits.",
                "All shortlisted proposals comply with the requirements in the brief.",
                "The final set contains only options that meet every stated criterion.",
                "Each surviving proposal remains feasible under the supplied constraints.",
                "Nothing in the retained set violates the brief's explicit conditions.",
                "The shortlist now consists entirely of qualifying alternatives.",
                "Every retained approach passes the stated feasibility checks.",
                "The remaining concepts each conform to the supplied criteria.",
                "Only proposals that satisfy the full brief remain in the comparison.",
                "All selected candidates stay inside the declared boundaries.",
            ),
        ),
    ),
    "context_clarification": (
        (
            "clarification-validating-reply",
            ("There is a real reason this affected you.",),
            (
                "Your reaction has an understandable basis.",
                "It makes sense that this had an effect on you.",
                "The response you describe is understandable.",
                "What happened gives this feeling a real context.",
                "There is a clear basis for the way this landed.",
                "Your experience provides a valid reason for this reaction.",
                "This feeling did not arise without context.",
                "The situation offers a credible reason for your response.",
                "It is understandable that the event stayed with you.",
                "Your reaction fits the circumstances you described.",
                "The effect on you is grounded in what happened.",
                "This response is reasonable in light of the situation.",
            ),
        ),
    ),
    "conversation_empathy": (
        (
            "empathy-changing-intensity",
            ("The feeling has changed in intensity during the day.",),
            (
                "Its intensity has shifted over the course of the day.",
                "The feeling has grown stronger and weaker at different moments today.",
                "I have noticed the emotion changing in strength as the day passed.",
                "The reaction has not stayed at the same intensity today.",
                "Its strength has varied since the day began.",
                "The emotion has moved through several levels of intensity today.",
                "I felt the reaction change in force during the day.",
                "The feeling became more or less intense at different points today.",
                "Its weight has fluctuated as the day unfolded.",
                "The emotion has shifted noticeably in strength today.",
                "I experienced changes in how strongly I felt it during the day.",
                "The reaction's intensity has varied with time today.",
            ),
        ),
    ),
    "critique_revision": (
        (
            "critique-preserve-meaning",
            ("Preserve the author's supported purpose and meaning.",),
            (
                "Keep the author's evidence-backed intent intact.",
                "Retain the supported meaning and original purpose.",
                "Do not alter the purpose that the evidence sustains.",
                "Protect the author's documented intent during revision.",
                "Keep the supported message faithful to its original aim.",
                "Preserve both the evidenced meaning and intended function.",
                "Maintain the purpose without extending the underlying claim.",
                "Hold the author's supported intent constant while editing.",
                "Revise the form while retaining the evidenced purpose.",
                "Leave the supported meaning unchanged by the correction.",
                "Keep the original aim wherever the source supports it.",
                "Make the revision faithful to the documented intent.",
            ),
        ),
        (
            "critique-no-invention",
            ("Do not invent facts, evidence, or commitments during revision.",),
            (
                "Add no unsupported fact, proof, or promise to the revision.",
                "The edit must introduce neither new evidence nor new commitments.",
                "Revise without supplying facts or assurances absent from the source.",
                "Keep all added claims, evidence, and promises out of the correction.",
                "Do not extend the source with invented support or obligations.",
                "The corrected text may not create evidence, facts, or commitments.",
                "Limit the revision to information and promises already documented.",
                "Introduce no new factual basis, proof, or undertaking.",
                "The edit should remain inside the source's facts and commitments.",
                "Avoid adding any claim, support, or promise not already present.",
                "No invented detail or obligation belongs in the revised wording.",
                "Preserve the evidence boundary and existing commitment level.",
            ),
        ),
    ),
    "explanation_learning": (
        (
            "explanation-example-fit",
            ("Include one concrete example and explain why it fits.",),
            (
                "Use one specific example and connect it explicitly to the concept.",
                "Give a concrete case, then show how it demonstrates the idea.",
                "Add one grounded example with a clear explanation of its relevance.",
                "Illustrate the mechanism once and state why the case applies.",
                "Choose one tangible example and link each relevant part to the lesson.",
                "Provide a single practical case and explain its fit.",
                "Demonstrate the idea with one example whose connection is explicit.",
                "Offer one checkable instance and identify why it belongs here.",
                "Anchor the explanation in one concrete case and make the link visible.",
                "Use one real-world illustration and describe how it supports the concept.",
                "Supply one focused example together with its conceptual connection.",
                "Show the principle through one case and explain the match.",
            ),
        ),
        (
            "explanation-copy-order",
            (
                "The order in which the facts were copied does not determine the answer.",
            ),
            (
                "Copy order has no bearing on the answer.",
                "The answer does not depend on which fact was copied first.",
                "Reordering the supplied facts would leave the conclusion unchanged.",
                "Sequence of transcription is irrelevant to the result.",
                "The copied facts support the same answer in any order.",
                "Nothing in the conclusion follows from the facts' copied sequence.",
                "The arrangement of copied facts does not control the outcome.",
                "Treat fact order as incidental rather than evidential.",
                "The result comes from the facts, not their transcription order.",
                "No inference should rely on where a copied fact appears.",
                "Changing the order of the facts would not change the answer.",
                "Copied position is not a deciding feature of the evidence.",
            ),
        ),
    ),
    "extraction_classification": (
        (
            "extraction-traceable-values",
            (
                "Make every extracted value traceable to the source text.",
                "Link values to source fields.",
            ),
            (
                "Keep a visible source basis for every extracted value.",
                "Each returned value must map back to its source field.",
                "Preserve field-level provenance throughout the extraction.",
                "Make the origin of every populated field verifiable.",
                "Tie each extracted value directly to supporting source text.",
                "Retain a clear source link for all returned fields.",
                "Every non-null value should have an identifiable source location.",
                "Keep the mapping from source fields to output values explicit.",
                "Allow each extracted value to be checked against the input.",
                "Maintain traceability between every output field and its evidence.",
                "Populate fields only where their source can be identified.",
                "Ensure that every returned value has a documented origin.",
            ),
        ),
        (
            "extraction-inconsistent-records",
            ("Equivalent records use inconsistent formats and field names.",),
            (
                "Records describing the same thing use different names and formats.",
                "Equivalent entries are represented with inconsistent fields and notation.",
                "The records align semantically but not in naming or format.",
                "Matching records arrive under incompatible labels and layouts.",
                "Field names and value formats vary across otherwise equivalent records.",
                "The source describes comparable records through inconsistent schemas.",
                "Equivalent information appears under different field labels and formats.",
                "The records need normalization because their schemas do not match.",
                "Comparable entries differ in both naming convention and representation.",
                "The same record type is encoded through several incompatible forms.",
                "Schema and formatting differences obscure equivalent records.",
                "Consistent information is stored with inconsistent names and value formats.",
            ),
        ),
    ),
    "grounded_qa": (
        (
            "grounded-unknown-request",
            ("Return unknown wherever a requested detail is absent.",),
            (
                "Mark every requested but undocumented detail as unknown.",
                "Use unknown for any requested fact the source does not provide.",
                "Leave absent requested information explicitly unresolved.",
                "Report an unknown value whenever the source is silent.",
                "Do not fill requested fields that lack source support.",
                "Label every unsupported requested detail as unknown.",
                "Keep undocumented parts of the request unresolved.",
                "Represent source omissions with an explicit unknown.",
                "Answer supported fields and mark all remaining ones unknown.",
                "Treat any requested value missing from the record as unknown.",
                "State that a detail is unknown when no source text establishes it.",
                "Preserve uncertainty for each requested fact absent from the source.",
            ),
        ),
    ),
    "planning_comparison": (
        (
            "planning-major-disruption",
            ("Reserve capacity for major disruption.",),
            (
                "Keep spare capacity available for a serious disruption.",
                "Preserve enough reserve to absorb a major interruption.",
                "Leave operational room for a high-impact disruption.",
                "Hold back capacity for an unexpected major event.",
                "Maintain a reserve against substantial disruption.",
                "Do not allocate the capacity needed for serious interruption.",
                "Protect sufficient headroom for a major failure.",
                "Keep a contingency reserve for significant disruption.",
                "Set aside capacity to handle a severe interruption.",
                "Retain enough slack for a major operational disturbance.",
                "Preserve emergency capacity throughout the plan.",
                "Leave a usable buffer for high-impact disruption.",
            ),
        ),
        (
            "planning-reversible-direction",
            ("Steps should preserve the ability to change direction.",),
            (
                "Order the steps so the plan can still change course.",
                "Keep each stage reversible enough to permit redirection.",
                "Preserve room to alter direction as the sequence advances.",
                "The chosen order must not lock the plan in too early.",
                "Use steps that retain a practical path to change course.",
                "Sequence commitments so a later correction remains possible.",
                "Maintain reversibility while moving through the plan.",
                "Avoid any early step that prevents a change in direction.",
                "Keep the sequence adaptable until key facts are confirmed.",
                "Each stage should leave a feasible alternative path open.",
                "Arrange commitments to preserve future choice.",
                "Let the plan progress without losing the option to redirect.",
            ),
        ),
    ),
    "reasoning_verification": (
        (
            "reasoning-supplied-assumptions",
            (
                "Use only the assumption used by the reasoning.",
                "Use only the values and rules supplied in the problem.",
            ),
            (
                "Base the calculation solely on the stated values and rules.",
                "Introduce no assumption beyond those supplied in the problem.",
                "Keep every inference within the given quantities and conditions.",
                "Use only the premises explicitly established by the question.",
                "Do not extend the calculation with an unstated assumption.",
                "Restrict the reasoning to the provided values and constraints.",
                "Let the supplied rules and numbers determine the full solution.",
                "Rely exclusively on the assumptions present in the prompt.",
                "Keep the derivation inside the problem's stated information.",
                "No external premise should enter the computation.",
                "Use the given quantities without adding another condition.",
                "Treat the problem statement as the complete reasoning boundary.",
            ),
        ),
    ),
    "safety_uncertainty": (
        (
            "safety-harm-first",
            ("Prioritize immediate harm reduction over detailed analysis.",),
            (
                "Reduce the immediate risk before attempting a detailed analysis.",
                "Put urgent harm prevention ahead of a complete explanation.",
                "Address immediate safety before exploring the situation in depth.",
                "Use the fastest protective step before adding analytical detail.",
                "Give priority to near-term harm reduction rather than exhaustive analysis.",
                "First lower the risk; detailed interpretation can follow later.",
                "Immediate protection matters more than a comprehensive account.",
                "Lead with the action that limits harm, not with extended analysis.",
                "Stabilize the risk before pursuing further explanation.",
                "Choose prompt protection over analytical completeness.",
                "Handle the safety concern first and defer nonessential detail.",
                "Begin by containing possible harm before examining every cause.",
            ),
        ),
    ),
    "summarization_synthesis": (
        (
            "summary-central-detail",
            ("Distinguish central information from supporting detail.",),
            (
                "Separate the main point from secondary evidence.",
                "Keep decisive information distinct from supporting material.",
                "Identify what is central and what merely adds context.",
                "Do not give background detail the weight of the main conclusion.",
                "Differentiate core information from explanatory support.",
                "Make the primary result clear apart from subsidiary detail.",
                "Preserve the hierarchy between decisive and supporting facts.",
                "Keep the central record visible while compressing its context.",
                "Separate essential content from material that only supports it.",
                "Show which information drives the outcome and which is secondary.",
                "Organize the summary around the core rather than its background.",
                "Treat supporting detail as context, not as the central decision.",
            ),
        ),
        (
            "summary-attribution",
            ("Keep speakers or sources attached to claims when attribution matters.",),
            (
                "Retain source attribution wherever it changes how a claim should be read.",
                "Keep each material claim linked to the relevant speaker or source.",
                "Preserve attribution for claims whose origin affects interpretation.",
                "Name the source when ownership of a statement matters.",
                "Do not detach consequential claims from their speakers.",
                "Carry source identity with any claim that depends on attribution.",
                "Keep speaker and claim connected where responsibility matters.",
                "Make the origin of attributed statements visible in the summary.",
                "Preserve who said what when that distinction is meaningful.",
                "Attach claims to their sources whenever provenance affects the record.",
                "Retain the relevant speaker for any source-dependent assertion.",
                "Do not merge attributed claims into an anonymous consensus.",
            ),
        ),
    ),
    "troubleshooting": (
        (
            "troubleshooting-reversible-step",
            ("Every diagnostic step must be reversible.",),
            (
                "Make each diagnostic action safe to undo.",
                "Use only diagnostic steps that can be reversed.",
                "Every test must leave a reliable rollback path.",
                "Do not include an irreversible action in the diagnostic sequence.",
                "Keep all investigative changes fully recoverable.",
                "Each test should permit restoration of the prior state.",
                "Preserve reversibility throughout the diagnosis.",
                "Limit the procedure to changes that can be rolled back.",
                "Ensure that every diagnostic modification is temporary.",
                "No test may remove the ability to restore the baseline.",
                "Use recoverable actions for every stage of diagnosis.",
                "Keep a clear reversal path behind each diagnostic step.",
            ),
        ),
    ),
    "writing_transformation": (
        (
            "writing-explicit-next-step",
            ("Make ownership and the requested next step explicit.",),
            (
                "State clearly who owns the work and what should happen next.",
                "Keep both responsibility and the requested action explicit.",
                "Identify the owner together with the next required step.",
                "Make the responsible person and immediate request unambiguous.",
                "Name who acts next and describe the expected action.",
                "Preserve a clear owner and a direct call to action.",
                "Show responsibility and the next move without implication.",
                "Keep the assignment and requested follow-up visible.",
                "Specify both ownership and the action now required.",
                "Leave no ambiguity about who should do what next.",
                "Attach the next step to its responsible owner.",
                "Express the requested action with an identifiable owner.",
            ),
        ),
        (
            "writing-plain-language",
            ("Prefer plain language over jargon and inflated phrasing.",),
            (
                "Use direct language instead of jargon or grand wording.",
                "Choose simple terms and remove inflated phrasing.",
                "Write plainly without technical shorthand or exaggeration.",
                "Replace jargon and overstatement with clear everyday language.",
                "Keep the wording straightforward and proportionate.",
                "Favor familiar words over specialized or inflated language.",
                "Make the prose clear without ornamental claims.",
                "Use concise ordinary language throughout the revision.",
                "Avoid jargon, euphemism, and unnecessary emphasis.",
                "Keep the register plain and free of grandiose wording.",
                "Express the source directly with no inflated terminology.",
                "Prefer accessible wording that says exactly what happened.",
            ),
        ),
        (
            "writing-rough-source",
            ("The source is a rough collection of notes.",),
            (
                "The source consists of unpolished notes.",
                "The available material is still in note form.",
                "The source text has not yet been shaped into prose.",
                "The input is a loose set of working notes.",
                "Only rough notes are available as source material.",
                "The supplied text is an unfinished collection of points.",
                "The source remains a draft-like set of notes.",
                "The material arrives as disconnected working notes.",
                "The input records facts without polished presentation.",
                "The source is structured as preliminary notes rather than prose.",
                "The supplied content is useful but still rough in form.",
                "The source contains unedited notes that need a clear register.",
            ),
        ),
    ),
}


# Second-pass reservoirs cover source facts that only become dominant after a
# broader phrase has been diversified. Keeping these separate makes the audit
# history explicit and avoids hiding them in the semantic card definitions.
SECOND_PASS_LITERAL_RESERVOIRS: dict[
    str, tuple[tuple[str, tuple[str, ...], tuple[str, ...]], ...]
] = {
    "brainstorming_creativity": (
        (
            "brainstorm-cheap-test",
            ("Give each idea a cheap test.",),
            (
                "Attach a low-cost trial to every idea.",
                "Define one inexpensive test for each proposal.",
                "Pair every option with a small affordable experiment.",
                "Give each concept a quick test that costs little.",
                "Specify a cheap validation step for every idea.",
                "Add one lightweight trial to each alternative.",
                "Make every proposal testable through a low-cost check.",
                "Identify an inexpensive first experiment for each option.",
                "Include one small-budget test beside every idea.",
                "Provide a cheap way to validate each proposal.",
                "For every concept, state one affordable test.",
                "Link each alternative to a minimal-cost experiment.",
            ),
        ),
        (
            "brainstorm-audience-result",
            ("Each option remains directed to the audience named in the brief.",),
            (
                "Every option continues to serve the audience identified by the brief.",
                "The intended audience remains visible in each proposal.",
                "All alternatives stay focused on the brief's named audience.",
                "Each retained concept is designed for the specified audience.",
                "The proposals consistently address the people named in the brief.",
                "No option loses sight of its intended audience.",
                "Every alternative remains appropriate for the target audience.",
                "The audience specified in the brief still guides all options.",
                "Each proposal clearly serves the stated audience.",
                "All retained ideas preserve their audience fit.",
                "The target audience is respected throughout the option set.",
                "Every proposed path remains aligned with the named audience.",
            ),
        ),
        (
            "brainstorm-trace-id",
            ("The record identifier is included only for traceability.",),
            (
                "The identifier appears solely to make the record traceable.",
                "Use the record code only as a provenance reference.",
                "The included identifier serves traceability and nothing else.",
                "Treat the record identifier as metadata for tracing the source.",
                "The code is present only to link back to the record.",
                "Record identification is retained solely for provenance.",
                "The identifier has no role beyond source traceability.",
                "Keep the code only as a way to locate the originating record.",
                "The record ID is metadata rather than part of the result.",
                "No meaning should be inferred from the traceability identifier.",
                "The code exists only to preserve a traceable reference.",
                "Use the identifier for provenance, not as answer content.",
            ),
        ),
    ),
    "context_clarification": (
        (
            "clarification-outside-weight",
            ("That carries more weight than it may seem from outside.",),
            (
                "Its importance may not be obvious to someone outside the situation.",
                "An outside observer could easily underestimate how much that matters.",
                "The effect is heavier than it might appear from a distance.",
                "Someone not involved may miss the weight this carries.",
                "That detail matters more internally than its surface suggests.",
                "Its significance is easy to overlook from the outside.",
                "The situation has more emotional weight than an observer might assume.",
                "What looks small externally can still feel substantial here.",
                "This may carry greater importance than others can immediately see.",
                "The impact is not fully visible to an outside perspective.",
                "From within the situation, that detail has real weight.",
                "Its effect can be meaningful even if it appears modest externally.",
            ),
        ),
    ),
    "conversation_empathy": (
        (
            "empathy-no-assumption",
            ("We do not have to assume the answer.",),
            (
                "There is no need to decide what it means before exploring it.",
                "We can examine the feeling without guessing its conclusion.",
                "The answer can remain open while we understand the experience.",
                "Nothing requires us to settle the meaning in advance.",
                "We can stay curious instead of assuming an explanation.",
                "The situation can be explored without forcing an answer.",
                "It is fine to leave the conclusion undecided for now.",
                "We can work from what you noticed rather than guess the rest.",
                "No immediate assumption is needed to continue.",
                "Understanding can come before any final interpretation.",
                "We can hold the question open while considering the details.",
                "The response does not need a predetermined answer.",
            ),
        ),
    ),
    "critique_revision": (
        (
            "critique-concrete-change",
            ("Make every recommended change concrete enough to apply.",),
            (
                "Express each recommendation as a change the author can perform.",
                "Keep every suggested revision specific and actionable.",
                "Turn each recommendation into a clearly applicable edit.",
                "Describe proposed changes with enough detail to implement them.",
                "Avoid recommendations that are too vague to use.",
                "Each suggested change should identify a practical revision.",
                "Make the corrective action explicit in every recommendation.",
                "State edits precisely enough for direct application.",
                "Ensure each recommendation can be translated into a concrete edit.",
                "Use specific revision instructions instead of general criticism.",
                "Every proposed improvement must be operationally clear.",
                "Keep the recommendations detailed enough to guide revision.",
            ),
        ),
        (
            "critique-strong-evidence-weak-order",
            ("The draft has strong evidence but weak organization.",),
            (
                "The evidence is solid, but the draft is poorly organized.",
                "Strong support is present even though the structure is weak.",
                "The draft's evidence works better than its organization.",
                "Good evidence is obscured by an ineffective structure.",
                "The material is well supported but arranged unclearly.",
                "Evidence quality is high while the organization remains weak.",
                "The draft contains credible support in a confusing order.",
                "Its factual basis is strong, but its structure needs revision.",
                "The argument has sound evidence without a clear organization.",
                "Support is persuasive, whereas the presentation is disordered.",
                "The evidence should be retained while the draft is reorganized.",
                "A structural problem, not an evidence shortage, limits the draft.",
            ),
        ),
        (
            "critique-repeat-failed-action",
            ("Please repeat the failed action to confirm that it now works.",),
            (
                "Repeat the action that failed so the result can be verified.",
                "Try the affected action again to check whether it succeeds.",
                "Confirm the fix by rerunning the previously failed action.",
                "Reproduce the action once more and report whether it now works.",
                "Test the former failure path again before declaring resolution.",
                "Run the failed action another time to verify the outcome.",
                "Check the reported fix through one repeat of the affected action.",
                "Attempt the operation again so its status can be confirmed.",
                "Use a fresh run of the failed action as the verification step.",
                "Repeat the operation that failed and observe the current result.",
                "Verify recovery by retrying the original failed action.",
                "Perform the affected action again before treating the issue as resolved.",
            ),
        ),
        (
            "critique-rollback-check",
            (
                "Verify the application before deleting anything, and retain rollback until the checks pass.",
            ),
            (
                "Keep rollback available and delete nothing until the application is verified.",
                "Test the application first; preserve the recovery path until all checks pass.",
                "Do not remove any file before verification, and retain a working rollback option.",
                "Confirm the application works before deletion while keeping recovery possible.",
                "Preserve the original state until every application check succeeds.",
                "Complete verification before deleting anything or retiring rollback.",
                "Keep all recoverable copies until the application passes its checks.",
                "Deletion comes only after verification and a retained rollback path.",
                "Validate the application fully before removing the old state.",
                "Maintain rollback through the checks and postpone deletion until success.",
                "Verify first, keep recovery available, and delete only after passing checks.",
                "Nothing should be deleted until the application and rollback path are confirmed.",
            ),
        ),
    ),
    "extraction_classification": (
        (
            "extraction-keep-traceable",
            ("Keep every extracted value traceable to the source text.",),
            (
                "Preserve a source-text link for every extracted value.",
                "Each returned value must remain verifiable in the input.",
                "Tie all populated output fields to supporting source text.",
                "Retain field-level provenance for every extracted value.",
                "Make the origin of each non-null value identifiable.",
                "Keep a visible mapping from each value to its source evidence.",
                "Allow every extracted value to be checked against the source.",
                "Populate no value without a traceable source location.",
                "Maintain explicit provenance across all extracted fields.",
                "Every returned value needs a documented source basis.",
                "Keep source support attached to each extracted result.",
                "Ensure all output values can be traced back to the text.",
            ),
        ),
        (
            "extraction-requested-schema",
            ("Use only fields defined by the requested schema.",),
            (
                "Return no field outside the requested schema.",
                "Limit the output to keys defined by the target schema.",
                "Do not introduce fields absent from the requested structure.",
                "Keep the result inside the supplied field list.",
                "Populate only the schema keys named in the request.",
                "Exclude any output field not defined by the requested schema.",
                "The requested schema is the complete boundary for returned fields.",
                "Use exactly the defined fields and no additional keys.",
                "Keep every output key within the specified schema.",
                "Add no field beyond those explicitly requested.",
                "Restrict the JSON object to the target schema's fields.",
                "Only schema-defined keys belong in the result.",
            ),
        ),
    ),
    "planning_comparison": (
        (
            "planning-uncertain-input",
            ("One important input remains uncertain.",),
            (
                "A material input has not yet been confirmed.",
                "One decision-relevant fact remains unresolved.",
                "The comparison still depends on an uncertain input.",
                "A key piece of information is not yet established.",
                "One important decision variable remains unknown.",
                "The plan contains a material unconfirmed input.",
                "A relevant fact still needs verification.",
                "One key input remains open at this stage.",
                "The decision cannot treat one unresolved input as certain.",
                "A consequential detail remains pending confirmation.",
                "One input that affects the choice is still uncertain.",
                "The available record leaves a key planning fact unresolved.",
            ),
        ),
        (
            "planning-hard-requirement",
            ("One stated requirement cannot be traded away.",),
            (
                "One explicit requirement is non-negotiable.",
                "A stated condition must be satisfied without trade-off.",
                "The plan cannot exchange away one mandatory requirement.",
                "One declared constraint remains absolute.",
                "A hard requirement must be preserved in every option.",
                "No preference can override one mandatory condition.",
                "The comparison includes one requirement that cannot be relaxed.",
                "One stated boundary is not available for compromise.",
                "Every candidate must satisfy the non-negotiable requirement.",
                "A required condition remains fixed throughout the decision.",
                "The plan may trade preferences but not this stated requirement.",
                "One mandatory criterion must remain intact.",
            ),
        ),
    ),
    "practical_action": (
        (
            "practical-partial-reference",
            ("Only partial reference information is currently available.",),
            (
                "The available reference record is incomplete.",
                "Only part of the needed reference information has been confirmed.",
                "Current records provide an incomplete reference.",
                "Some required reference details are still missing.",
                "The reference information available now is only partial.",
                "No complete reference record is currently present.",
                "The request relies on reference data that remains incomplete.",
                "Only a subset of the necessary reference details is available.",
                "The present reference material does not cover every required field.",
                "A complete reference still needs to be obtained.",
                "Current evidence contains only partial reference details.",
                "The authoritative reference is not yet complete.",
            ),
        ),
        (
            "practical-unconfirmed-request",
            ("A request exists but has not been confirmed.",),
            (
                "The request is recorded but remains unconfirmed.",
                "A submitted request has not yet received confirmation.",
                "The record shows a request without confirmed status.",
                "Confirmation is still missing for the existing request.",
                "A request is present, although its acceptance is unresolved.",
                "The current request has not been formally confirmed.",
                "The request exists in the record but not as a confirmed action.",
                "No confirmation has yet validated the recorded request.",
                "An outstanding request remains pending confirmation.",
                "The request has been made but its status is not established.",
                "A recorded request still awaits authoritative confirmation.",
                "The available information does not confirm the request.",
            ),
        ),
    ),
    "safety_uncertainty": (
        (
            "safety-format-values",
            ("Formatting differences in the source do not change the stated values.",),
            (
                "Different source formatting leaves the reported values unchanged.",
                "Treat format variation as irrelevant to the stated values.",
                "The values remain the same despite differences in presentation.",
                "Do not alter a value merely because the source formats it differently.",
                "Source layout differences have no effect on the recorded values.",
                "Preserve each stated value across formatting variations.",
                "Changes in representation do not establish changes in value.",
                "The source's formatting varies, but its values do not.",
                "Keep the reported values constant when normalizing format.",
                "Presentation differences should not modify the supplied values.",
                "Separate formatting variation from factual value changes.",
                "No value changes are supported by format differences alone.",
            ),
        ),
        (
            "safety-ambiguous-harm",
            ("The request is ambiguous but could create meaningful harm.",),
            (
                "The request lacks clarity and carries a material risk of harm.",
                "Ambiguity in the request does not remove its potential for serious harm.",
                "The unclear request may still lead to a consequential risk.",
                "Meaningful harm remains possible even though the request is ambiguous.",
                "The request is underspecified in a way that may create real harm.",
                "Uncertainty about intent coexists with a nontrivial safety risk.",
                "The ambiguous situation has potentially harmful consequences.",
                "A lack of clarity leaves open a meaningful path to harm.",
                "The request cannot be safely assumed harmless while it remains unclear.",
                "Material risk is present despite ambiguity in the requested action.",
                "The request is unclear, but its downside could be consequential.",
                "Ambiguous wording still raises a credible risk of harm.",
            ),
        ),
        (
            "safety-no-code-links",
            ("Do not share the code or use links from the message.",),
            (
                "Share no code and open none of the message's links.",
                "Do not provide the code or follow any link in the message.",
                "Keep the code private and avoid all links supplied by the sender.",
                "Neither disclose the code nor use the embedded links.",
                "Ignore the message links and do not reveal the code.",
                "Treat both the requested code and supplied links as unsafe.",
                "Do not enter the code or navigate through the message.",
                "Refuse to share the code and avoid clicking the provided links.",
                "Keep the code confidential and use no link from that contact.",
                "Do not act on the links or send the authentication code.",
                "Avoid the message's links and disclose no security code.",
                "No code should be shared, and no included link should be opened.",
            ),
        ),
        (
            "safety-official-provider",
            (
                "End the contact and reach the provider through its official app or published number.",
            ),
            (
                "Stop communicating there and contact the provider through an official channel.",
                "End the exchange, then use the provider's verified app or published number.",
                "Leave the unverified contact and reach support through the official application.",
                "Discontinue the message thread and call a number published by the provider.",
                "Use no channel from the message; contact the provider independently instead.",
                "Close the contact and open the provider's official app for support.",
                "Verify the issue through a published provider number after ending the exchange.",
                "Stop responding and use only an independently verified provider channel.",
                "Reach the provider from its official site or app, not from the message.",
                "Terminate the contact before calling the provider's documented number.",
                "Move the inquiry to a verified provider channel and abandon this contact.",
                "End communication with the sender and contact official support directly.",
            ),
        ),
    ),
    "summarization_synthesis": (
        (
            "summary-preserve-disagreement",
            (
                "Preserve uncertainty and disagreement instead of converting them into consensus.",
            ),
            (
                "Keep unresolved uncertainty and disagreement visible rather than implying agreement.",
                "Do not turn differing views or open questions into a false consensus.",
                "Retain both disagreement and uncertainty in the summarized record.",
                "Represent unresolved differences without smoothing them into agreement.",
                "The summary must not erase uncertainty or conflicting positions.",
                "Keep open questions and disagreement distinct from settled conclusions.",
                "Do not report consensus where the source contains uncertainty or dissent.",
                "Preserve the record's unresolved and contested elements.",
                "Leave uncertainty and differing positions explicit.",
                "Avoid merging conflicting evidence into a single agreed view.",
                "Carry forward unresolved disagreement without resolving it implicitly.",
                "Make uncertainty and dissent visible in the final synthesis.",
            ),
        ),
        (
            "summary-mixed-evidence",
            ("The material mixes decisive evidence with secondary detail.",),
            (
                "The source combines decision-critical evidence with supporting detail.",
                "Decisive information appears alongside less important context.",
                "The material does not separate core evidence from secondary points.",
                "Primary evidence and background detail are intermingled.",
                "The source blends outcome-driving facts with supplementary material.",
                "Important evidence is mixed together with contextual detail.",
                "The record combines central findings and secondary observations.",
                "Decisive facts are not yet distinguished from supporting context.",
                "The material contains both essential evidence and ancillary detail.",
                "Core information is embedded among points of lesser importance.",
                "The source places critical and supplementary evidence at the same level.",
                "Decision-relevant facts are mixed with background information.",
            ),
        ),
    ),
    "troubleshooting": (
        (
            "troubleshooting-no-admin",
            ("Administrator access is unavailable.",),
            (
                "No administrator access is available.",
                "The diagnostic cannot use administrator privileges.",
                "Administrative access is not part of the available environment.",
                "No elevated account can be used for this test.",
                "The procedure must work without administrator rights.",
                "System-level privileges are unavailable.",
                "The affected setup provides no administrative access.",
                "Use only actions that require no elevated permissions.",
                "An administrator account cannot be accessed.",
                "The diagnostic boundary excludes privileged access.",
                "No elevated permission is available for the investigation.",
                "The test environment lacks administrator rights.",
            ),
        ),
        (
            "troubleshooting-copy-order",
            (
                "The order in which the facts were copied does not determine the answer.",
            ),
            (
                "Copy order has no bearing on the diagnostic conclusion.",
                "The answer does not follow from which fact was copied first.",
                "Reordering the supplied facts leaves the diagnosis unchanged.",
                "Sequence of transcription is irrelevant to the result.",
                "The facts support the same answer in any copied order.",
                "Nothing in the diagnosis depends on the copied sequence.",
                "Arrangement of copied facts does not control the outcome.",
                "Treat fact order as incidental rather than diagnostic evidence.",
                "The conclusion comes from the facts, not their transcription order.",
                "No diagnostic inference should rely on copied position.",
                "Changing fact order would not change the answer.",
                "Copied sequence is not a deciding feature of the evidence.",
            ),
        ),
    ),
    "writing_transformation": (
        (
            "writing-admin-label",
            (
                "An administrative label in the record is not part of the requested result.",
            ),
            (
                "Exclude the record's administrative label from the requested output.",
                "The administrative tag is metadata rather than answer content.",
                "Do not carry the record label into the final result.",
                "The requested text does not include the administrative identifier.",
                "Treat the administrative label as source metadata only.",
                "Omit the internal record label from the transformed text.",
                "The record tag has no place in the requested deliverable.",
                "Keep the administrative identifier outside the final prose.",
                "Do not present the internal label as part of the result.",
                "The output should exclude source-side administrative metadata.",
                "Remove the record label while preserving its factual content.",
                "Only the message content, not its administrative tag, belongs in the answer.",
            ),
        ),
        (
            "writing-register-shift",
            ("The draft shifts between formal and conversational language.",),
            (
                "The draft moves inconsistently between formal and conversational registers.",
                "Its tone alternates between formal prose and casual speech.",
                "The source uses an uneven mix of formal and conversational language.",
                "Register changes make the draft tonally inconsistent.",
                "The wording moves back and forth between official and casual styles.",
                "The draft lacks a stable register across its sentences.",
                "Formal language and conversational phrasing are mixed unevenly.",
                "The source's tone changes without a clear reason.",
                "The draft combines registers that do not remain consistent.",
                "Its presentation shifts between institutional and informal language.",
                "A changing register makes the source feel uneven.",
                "The draft needs one consistent tone instead of formal-casual shifts.",
            ),
        ),
        (
            "writing-confirm-after-review",
            ("We will confirm resolution after that review.",),
            (
                "Resolution will be confirmed once that review is complete.",
                "After the review, we will state whether the issue is resolved.",
                "We will confirm the outcome following completion of the review.",
                "The review must finish before resolution is confirmed.",
                "Confirmation of resolution will follow that review.",
                "Once reviewed, the issue's resolution status will be confirmed.",
                "We will report resolution only after completing the review.",
                "The final confirmation comes after the review step.",
                "Resolution remains provisional until that review is done.",
                "We will provide a confirmed outcome when the review concludes.",
                "Completion of the review precedes any resolution confirmation.",
                "A resolution update will be issued after the review.",
            ),
        ),
    ),
}


# Full-sentence alternatives for semantic cases that still crossed the global
# five-percent ceiling after generic scaffolding had been diversified.  These
# are authored paraphrases of the same fact; they do not create new examples,
# labels, constraints, or card axes.
THIRD_PASS_LITERAL_RESERVOIRS: dict[
    str, tuple[tuple[str, tuple[str, ...], tuple[str, ...]], ...]
] = {
    "brainstorming_creativity": (
        (
            "brainstorm-mechanism-difference",
            ("Make options differ in mechanism, not wording.",),
            (
                "Make each option use a genuinely different mechanism.",
                "Distinguish the proposals by how they work rather than by phrasing.",
                "Vary the operating mechanism across options, not merely the words.",
                "Each proposal must take a different functional approach.",
                "Ensure that the alternatives differ in method instead of wording.",
                "Use distinct ways of achieving the goal for every option.",
                "Separate the ideas through their mechanisms, not their labels.",
                "The alternatives should work differently from one another.",
                "Change the underlying approach between proposals rather than the prose.",
                "Give every option its own means of producing the result.",
                "Do not present one mechanism under several verbal variations.",
                "Build diversity into the method used by each proposal.",
            ),
        ),
        (
            "brainstorm-scale-test",
            (
                "The selected option can be tested at the stated scale before expansion.",
            ),
            (
                "The chosen option supports a trial at the stated scale before expansion.",
                "A bounded test can precede any wider use of the selected proposal.",
                "The preferred idea can first be validated within the specified scale.",
                "Before expanding, test the selected approach under the recorded limits.",
                "The option permits an initial trial no larger than the stated scope.",
                "Validate the chosen proposal at its current scale prior to growth.",
                "A small-scale trial remains available before broader deployment.",
                "The selected path can be evaluated under the brief's present limits.",
                "Expansion follows only after a test at the specified scale.",
                "The proposal offers a contained trial before any increase in scope.",
                "Start by testing the preferred option within the stated capacity.",
                "Its first validation can remain inside the scale defined by the brief.",
            ),
        ),
        (
            "brainstorm-outcome-review",
            ("Outcome review: Each retained option satisfies the stated criteria.",),
            (
                "Outcome review: all retained options meet the stated criteria.",
                "The outcome check confirms that every retained proposal fits the criteria.",
                "Reviewing the result shows that the kept options satisfy the brief.",
                "Each remaining proposal clears the stated outcome conditions.",
                "The retained set stays consistent with every recorded criterion.",
                "All options kept after review remain eligible under the brief.",
                "The outcome assessment leaves only proposals that fit the criteria.",
                "Every retained alternative passes the stated result check.",
                "The final option set conforms to the requirements in the brief.",
                "No retained proposal falls outside the recorded outcome criteria.",
                "The result review confirms compliance across the retained alternatives.",
                "Each option still under consideration satisfies the defined criteria.",
            ),
        ),
    ),
    "conversation_empathy": (
        (
            "empathy-response-fits",
            ("Your response fits what happened.",),
            (
                "Your reaction is understandable in light of what happened.",
                "What you felt makes sense in that situation.",
                "That response is consistent with the event you described.",
                "The reaction you noticed follows understandably from the experience.",
                "It is reasonable that the event brought up that feeling.",
                "Your account gives a clear context for this reaction.",
                "Nothing about that response seems out of place here.",
                "The feeling matches the circumstances you experienced.",
                "Given the event, your reaction is easy to understand.",
                "That emotional response belongs within the experience you described.",
                "The situation provides a credible reason for what you felt.",
                "Your reaction reflects the pressure present in that moment.",
            ),
        ),
    ),
    "critique_revision": (
        (
            "critique-main-point-hidden",
            ("The main point is present but difficult to identify.",),
            (
                "The central point exists, but the draft does not make it easy to find.",
                "Readers must work too hard to locate the main message.",
                "The draft contains its key point without presenting it clearly.",
                "A central claim is available, although it remains buried.",
                "The intended message is there but lacks visible emphasis.",
                "The main idea can be recovered only after unnecessary effort.",
                "The draft obscures a point that should be immediately identifiable.",
                "Its principal message is present yet poorly surfaced.",
                "The core statement is difficult to distinguish from surrounding details.",
                "Readers can infer the main point, but the text does not foreground it.",
                "The message has a center, though its structure hides that center.",
                "The draft needs to expose the key point it already contains.",
            ),
        ),
        (
            "critique-backup-update",
            ("Back up the old folder and install the update separately.",),
            (
                "Preserve a backup of the existing folder, then install the update separately.",
                "Install the update apart from the original after backing up that folder.",
                "First copy the old folder safely; test the update in a separate location.",
                "Keep the original folder backed up while the update is installed elsewhere.",
                "Create a recoverable copy before placing the update in an isolated folder.",
                "Protect the old installation, then stage the update independently.",
                "Retain the existing folder as a backup and separate the new installation.",
                "Before updating, secure the old folder and use another path for the install.",
                "Make the original recoverable, then test the update outside it.",
                "Copy the current folder first and install the replacement without overwriting it.",
                "Safeguard the old directory before trying the update in isolation.",
                "Leave the backed-up folder intact while installing the update separately.",
            ),
        ),
    ),
    "explanation_learning": (
        (
            "learning-rule-transfer-gap",
            ("The learner repeats the rule but cannot apply it.",),
            (
                "The learner can state the rule but not use it in a new case.",
                "Recall is present, while application of the rule remains weak.",
                "The rule can be repeated without yet transferring to practice.",
                "The learner remembers the wording but cannot perform the next application.",
                "Knowing the rule has not yet produced usable understanding.",
                "The learner recites the principle but struggles to act on it.",
                "Verbal recall is stronger than practical use of the rule.",
                "The principle is remembered, although transfer to an example fails.",
                "The learner knows the statement but not how to apply it.",
                "Repeating the rule does not yet lead to a correct use.",
                "The learner retains the definition while missing its application.",
                "The gap lies between recalling the rule and using it correctly.",
            ),
        ),
        (
            "learning-simple-opening",
            ("In simple terms,", "The central idea is that"),
            (
                "Put plainly,",
                "At its simplest,",
                "The basic principle is this:",
                "A direct explanation begins here:",
                "In everyday language,",
                "The key mechanism can be stated directly:",
                "The idea becomes clearer this way:",
                "The shortest accurate explanation is:",
                "In practical terms,",
                "The core relationship works as follows:",
                "A useful plain-language view is:",
                "The concept can be reduced to this:",
            ),
        ),
    ),
    "grounded_qa": (
        (
            "grounded-preserve-unknown",
            ("preserve unknown status for anything the source omits",),
            (
                "keep every omitted value explicitly unknown",
                "mark information absent from the source as unknown",
                "leave undocumented fields unresolved",
                "report source omissions without filling them",
                "retain uncertainty wherever the record is silent",
                "do not assign values to details the source omits",
                "treat every unsupported field as unknown",
                "preserve missing information rather than infer it",
                "state that unrecorded values remain unknown",
                "leave all source gaps unfilled",
                "identify undocumented details as unresolved",
                "keep absent facts outside the answer",
            ),
        ),
        (
            "grounded-architect-omitted",
            ("It does not name the original architect.",),
            (
                "The original architect is not named in the excerpt.",
                "No architect is identified by the available record.",
                "The source omits the name of the original architect.",
                "Nothing in the note identifies who designed it originally.",
                "The architect's identity is absent from the supplied evidence.",
                "The excerpt provides no name for the original designer.",
                "Who served as original architect is not recorded here.",
                "The note contains no attribution to an architect.",
                "No original design credit appears in the source.",
                "The available text leaves the architect unidentified.",
                "Architectural authorship is not documented in this record.",
                "The source establishes no identity for the original architect.",
            ),
        ),
    ),
    "planning_comparison": (
        (
            "planning-fixed-deadline",
            ("A fixed deadline limits the feasible sequence.",),
            (
                "The deadline restricts which sequence remains feasible.",
                "Only schedules that fit the fixed deadline can proceed.",
                "The available sequence is constrained by a hard completion date.",
                "Timing removes any sequence that exceeds the deadline.",
                "A hard date narrows the set of workable step orders.",
                "The feasible ordering must fit within the stated deadline.",
                "The schedule boundary determines which sequence can be used.",
                "Any workable sequence has to respect the fixed time limit.",
                "The deadline eliminates step orders that finish too late.",
                "A bounded delivery window constrains the possible sequence.",
                "The remaining plan order is limited by the completion date.",
                "Feasibility depends on finishing the sequence before the deadline.",
            ),
        ),
        (
            "planning-on-basis",
            ("On that basis,",),
            (
                "After applying those criteria,",
                "Given the completed comparison,",
                "With those constraints accounted for,",
                "Following that screening,",
                "Under the stated limits,",
                "From the eligible alternatives,",
                "Once the requirements are applied,",
                "According to this comparison,",
                "With feasibility established,",
                "After removing the disqualified options,",
                "Using the resulting evidence,",
                "The comparison therefore supports this choice:",
            ),
        ),
    ),
    "practical_action": (
        (
            "practical-failed-attempt",
            ("One reasonable attempt failed without resolving the task.",),
            (
                "A reasonable first attempt did not resolve the task.",
                "The initial bounded action failed to produce a resolution.",
                "One appropriate attempt has already ended without success.",
                "The task remains unresolved after a sensible first action.",
                "A prior reasonable step did not complete the work.",
                "The first appropriate approach left the issue open.",
                "An earlier bounded attempt failed to settle the task.",
                "The attempted resolution was reasonable but ineffective.",
                "One valid effort has been made and the problem remains.",
                "The prior action did not achieve the required result.",
                "A sensible attempt was completed without resolving the issue.",
                "The current state follows an unsuccessful but reasonable first try.",
            ),
        ),
    ),
    "safety_uncertainty": (
        (
            "safety-risk-not-urgency",
            ("The facts suggest risk but do not establish urgency.",),
            (
                "The available facts indicate risk without proving how urgent it is.",
                "Risk is plausible, but the evidence does not establish its urgency.",
                "The record supports caution while leaving the urgency unresolved.",
                "There is a safety signal, though its immediacy is not established.",
                "The facts justify care but not a definite urgency judgment.",
                "Potential risk is present without enough evidence to rate urgency.",
                "The information raises concern while leaving timing uncertain.",
                "A risk may exist, but the record cannot determine immediacy.",
                "The evidence supports a protective response without an urgency claim.",
                "Concern is warranted even though urgency remains unverified.",
                "The reported facts point to risk but do not fix its severity in time.",
                "A cautious boundary is needed because urgency cannot be confirmed.",
            ),
        ),
    ),
    "summarization_synthesis": (
        (
            "summary-reader-mismatch",
            ("The current summary does not match the reader's needs.",),
            (
                "The existing summary is not suited to what this reader needs.",
                "Its present form does not serve the intended reader.",
                "The summary needs a different emphasis for its audience.",
                "What is summarized now does not fit the reader's purpose.",
                "The current version misses information important to this reader.",
                "The audience requires a summary shaped differently from the existing one.",
                "The summary's focus does not align with the reader's needs.",
                "A reader-specific revision is needed for the current summary.",
                "The existing condensation is poorly matched to its audience.",
                "This reader needs a different balance of detail and emphasis.",
                "The present summary does not answer the audience's main need.",
                "Its current structure is not useful enough for the intended reader.",
            ),
        ),
        (
            "summary-minority-views",
            ("Retain different minority views.",),
            (
                "Keep distinct minority views visible.",
                "Preserve the differences among minority positions.",
                "Do not merge separate minority views.",
                "Report divergent minority positions independently.",
                "Maintain each minority view as a distinct point.",
                "Leave differing minority perspectives identifiable.",
                "Represent minority positions without collapsing their differences.",
                "Keep each dissenting view separate in the summary.",
                "Preserve disagreement among the minority accounts.",
                "Retain the individual minority perspectives.",
                "Do not turn several minority views into one consensus.",
                "Show where the minority positions differ from one another.",
            ),
        ),
    ),
    "writing_transformation": (
        (
            "writing-agenda-pending",
            ("The agenda is still pending.",),
            (
                "The agenda has not yet been finalized.",
                "No final agenda is available yet.",
                "The session agenda remains open.",
                "Agenda details are still awaiting confirmation.",
                "The final agenda will be provided later.",
                "The meeting agenda is not yet settled.",
                "A confirmed agenda is still unavailable.",
                "The agenda remains under preparation.",
                "Final agenda items have not been published.",
                "The session does not yet have a confirmed agenda.",
                "Agenda confirmation remains outstanding.",
                "The agenda is awaiting final review.",
            ),
        ),
    ),
}
