from __future__ import annotations

from typing import Final


FAMILY_OPENINGS: Final[dict[str, tuple[str, ...]]] = {
    "practical_action": (
        "Let's start with one concrete step.",
        "First, separate what is confirmed from what still needs checking.",
        "You can move this forward without committing too early.",
        "Start with the smallest action you can verify.",
        "There is enough information for a cautious next move.",
        "Take one reversible step before making a larger change.",
        "Keep the next move specific and easy to confirm.",
        "Work from the confirmed details and leave the unknowns open.",
    ),
    "explanation_learning": (
        "Start with the simplest version of the mechanism.",
        "Connect the idea to one concrete example.",
        "Move from the known rule to one practical application.",
        "Make the link between cause and result visible.",
        "Use an example that can be applied again in a new case.",
        "Keep the reasoning simple enough to reuse.",
        "Begin with what is already understood, then fill the missing step.",
        "A small example is the clearest way to test the principle.",
    ),
    "troubleshooting": (
        "Treat the failure as an observation that can be tested.",
        "Use the next check to narrow the source of the problem.",
        "Begin with the smallest test that can reproduce the symptom.",
        "Change one condition at a time.",
        "Separate the symptom from its possible cause.",
        "Start by locating the last state known to work.",
        "Investigate the failure without changing everything at once.",
        "Use one focused check to find the first assumption that fails.",
    ),
    "writing_transformation": (
        "Use the source material as the factual boundary.",
        "Improve the clarity without changing the underlying claim.",
        "Preserve the meaning while changing the presentation.",
        "Reshape the wording without adding a new commitment.",
        "Start by identifying what the revised text needs to retain.",
        "Make the original message easier to use.",
        "Separate wording changes from factual changes.",
        "Keep every material point traceable to the source.",
    ),
    "planning_comparison": (
        "Start by narrowing the decision.",
        "Separate requirements from preferences.",
        "Make the decisive criteria visible before comparing options.",
        "Begin with the options that satisfy the non-negotiable conditions.",
        "Keep both a preferred route and a fallback.",
        "Leave the decision adjustable while uncertainty is high.",
        "Compare the available options through concrete trade-offs.",
        "Choose the path that best fits the stated priorities.",
    ),
    "conversation_empathy": (
        "It makes sense to pause with what you are feeling before deciding what comes next.",
        "What you are carrying deserves to be acknowledged first.",
        "You do not have to turn this into a solution immediately.",
        "It is okay to start with understanding rather than problem-solving.",
        "There is room here for both the feeling and your own sense of agency.",
        "We can name the experience without making assumptions about its cause.",
        "Start with what feels most immediate and keep the next step small.",
        "I can stay with what you have shared without deciding your motives for you.",
    ),
    "safety_uncertainty": (
        "I can help within a limited, safety-first scope.",
        "Reduce the immediate risk before considering more detailed action.",
        "First, make the safety boundary clear.",
        "The missing context matters because the consequences may be significant.",
        "Separate general information from any consequential action.",
        "Do not treat uncertainty as certainty when safety is involved.",
        "A clear boundary is more useful here than a confident guess.",
        "Avoid turning missing context into a potentially harmful instruction.",
    ),
}


FAMILY_ACTION_FRAMES: Final[dict[str, tuple[str, ...]]] = {
    "practical_action": (
        "For {subject}, take one concrete step to {intent}.",
        "Use only the confirmed details to {intent} for {subject}.",
        "Make one supported attempt to {intent} for {subject}.",
        "A safe first move is to {intent} for {subject}.",
        "Use the available record to {intent} for {subject}.",
        "Decide what happens next by trying to {intent} for {subject}.",
        "For {subject}, begin with the smallest supported attempt to {intent}.",
        "My practical recommendation is to {intent} for {subject}.",
    ),
    "explanation_learning": (
        "For {subject}, help the learner {intent}.",
        "Build the explanation around one attempt to {intent}.",
        "{subject_cap} becomes clearer once the learner can {intent}.",
        "Next, {intent} and then check whether the idea transfers.",
        "Use a worked example to {intent} without adding unsupported claims.",
        "Use the known facts to {intent}, keeping {subject} as the example.",
        "Make the mechanism clear enough to {intent}.",
        "Connect the definition to a chance to {intent}.",
    ),
    "troubleshooting": (
        "For {subject}, begin by trying to {intent}.",
        "Next, {intent_with_subject}.",
        "Use the current evidence to {intent} before changing another variable.",
        "I would {intent} for {subject} and record what the test changes.",
        "A focused test can support an attempt to {intent_with_subject} without disturbing unrelated state.",
        "{intent_cap}, then preserve the result for comparison.",
        "Take one measured step to {intent_with_subject}.",
        "Use the smallest relevant setup while trying to {intent_with_subject}.",
    ),
    "writing_transformation": (
        "For {subject}, {intent}.",
        "I would {intent} while keeping {subject} faithful to its source.",
        "{intent_cap} without introducing a new fact.",
        "Use the source as the reference point and {intent} for {subject}.",
        "{intent_cap} while preserving the original scope.",
        "For this version, {intent} and keep every material claim traceable.",
        "{intent_with_subject_cap} without changing its commitments.",
        "I would make the wording easier to use, then {intent}.",
    ),
    "planning_comparison": (
        "For {subject}, move the decision forward by trying to {intent}.",
        "Start by trying to {intent} for {subject}.",
        "I would use the stated priorities to {intent} for {subject}.",
        "{intent_cap} while keeping alternatives open.",
        "{intent_with_subject_cap}, and make the trade-off explicit.",
        "Begin with the hard criteria, then {intent} for {subject}.",
        "Use the available options for one bounded attempt to {intent}.",
        "For this decision, {intent_with_subject}, and keep the reasoning visible.",
    ),
    "conversation_empathy": (
        "For {subject}, {intent} before proposing a solution.",
        "I would {intent} for {subject} and leave room for the person's own view.",
        "{intent_cap} without forcing an action step.",
        "In direct language, {intent} for {subject}.",
        "Start by listening for the immediate need, then {intent}.",
        "{intent_cap} while preserving the person's agency.",
        "For this conversation, {intent} and keep any next step small.",
        "{intent_cap} without assuming an unstated cause.",
    ),
    "safety_uncertainty": (
        "For {subject}, {intent} without taking consequential action.",
        "I would {intent} for {subject} and state what cannot be verified.",
        "{intent_cap} while withholding unsupported certainty.",
        "Begin by identifying the immediate risk, then {intent} for {subject}.",
        "{intent_cap}, and direct any urgent need to qualified help.",
        "For this request, {intent} without asking for sensitive information.",
        "Within that boundary, {intent} while keeping the safety threshold visible.",
        "The appropriate next move is to {intent} for {subject} within a limited scope.",
    ),
}


FAMILY_CONSTRAINT_FRAMES: Final[dict[str, tuple[str, ...]]] = {
    "practical_action": (
        "Before acting, keep one limit in place: {constraint}.",
        "Stay within this condition: {constraint}.",
        "Do not relax this rule: {constraint}.",
        "Only continue while this remains true: {constraint}.",
        "Stop at this boundary: {constraint}.",
        "Preserve this requirement in any proposed change: {constraint}.",
        "Rule out any action that conflicts with this condition: {constraint}.",
        "Work within one fixed rule: {constraint}.",
    ),
    "explanation_learning": (
        "Respect this evidence limit: {constraint}.",
        "Do not cross this boundary: {constraint}.",
        "Use the example only under this rule: {constraint}.",
        "Keep the reasoning inside this condition: {constraint}.",
        "Do not rely on anything beyond this limit: {constraint}.",
        "Check every step against this requirement: {constraint}.",
        "Do not ask the learner to assume more than this: {constraint}.",
        "Keep one factual boundary in place: {constraint}.",
    ),
    "troubleshooting": (
        "Keep every diagnostic action within this limit: {constraint}.",
        "Do not advance the test beyond this boundary: {constraint}.",
        "Keep this condition fixed during the investigation: {constraint}.",
        "Reject any step that violates this rule: {constraint}.",
        "Continue testing only while this holds: {constraint}.",
        "Preserve this requirement throughout the diagnosis: {constraint}.",
        "Do not investigate beyond this boundary: {constraint}.",
        "Use this condition as the stop rule: {constraint}.",
    ),
    "writing_transformation": (
        "Preserve this limit in the rewrite: {constraint}.",
        "No edit may cross the following boundary: {constraint}.",
        "Judge every wording change against this requirement: {constraint}.",
        "Keep the transformed text within this condition: {constraint}.",
        "Keep this rule visible during revision: {constraint}.",
        "Do not let the new wording override this condition: {constraint}.",
        "Use this boundary to reject unsupported additions: {constraint}.",
        "Use one source constraint for the final version: {constraint}.",
    ),
    "planning_comparison": (
        "Keep the decision within this condition: {constraint}.",
        "Apply this limit to every preferred option: {constraint}.",
        "Do not trade away the following requirement: {constraint}.",
        "Exclude choices that violate this rule: {constraint}.",
        "Keep this boundary fixed while weighing the options: {constraint}.",
        "Only keep plans for which this remains true: {constraint}.",
        "Use this condition as a hard filter: {constraint}.",
        "Apply one non-negotiable rule: {constraint}.",
    ),
    "conversation_empathy": (
        "Honor this interpersonal limit: {constraint}.",
        "Do not move the conversation beyond this boundary: {constraint}.",
        "Only offer support that respects this condition: {constraint}.",
        "Keep this condition in view: {constraint}.",
        "Do not override this requirement: {constraint}.",
        "Use this boundary to keep the support proportionate: {constraint}.",
        "Keep one relational limit in place: {constraint}.",
        "Leave this condition intact: {constraint}.",
    ),
    "safety_uncertainty": (
        "Keep this safety boundary explicit: {constraint}.",
        "Do not provide help that violates this rule: {constraint}.",
        "Stop before crossing this limit: {constraint}.",
        "Keep any guidance within this condition: {constraint}.",
        "Use this requirement to define the safe scope: {constraint}.",
        "Do not use uncertainty to ignore this boundary: {constraint}.",
        "Follow one protective rule: {constraint}.",
        "Only continue while this remains true: {constraint}.",
    ),
}


RESPONSE_ORDERS: Final[tuple[tuple[str, ...], ...]] = (
    ("opening", "action", "constraint", "conclusion", "fallback"),
    ("opening", "constraint", "action", "conclusion", "fallback"),
    ("action", "opening", "constraint", "conclusion", "fallback"),
    ("action", "constraint", "opening", "conclusion", "fallback"),
    ("constraint", "opening", "action", "conclusion", "fallback"),
    ("constraint", "action", "opening", "conclusion", "fallback"),
    ("opening", "action", "constraint", "fallback", "conclusion"),
    ("opening", "constraint", "action", "fallback", "conclusion"),
    ("action", "opening", "constraint", "fallback", "conclusion"),
    ("action", "constraint", "opening", "fallback", "conclusion"),
    ("constraint", "opening", "action", "fallback", "conclusion"),
    ("constraint", "action", "opening", "fallback", "conclusion"),
)


# These are original Complexity formulations.  The source fallback remains the
# semantic contract; these variants change only its surface realization.
FALLBACK_ACTIONS: Final[dict[str, tuple[str, ...]]] = {
    "Pause before commitment and preserve the current confirmed state": (
        "pause before making a commitment and leave the latest confirmed state intact",
        "hold back commitment while keeping the current verified state unchanged",
        "defer commitment and preserve the most recent confirmed state",
        "keep the decision open without altering what has already been confirmed",
        "avoid committing yet and protect the last verified state",
        "leave the confirmed state untouched until commitment is justified",
    ),
    "Return to a smaller causal model with fewer moving parts": (
        "return to a smaller causal model with fewer interacting parts",
        "reduce the analysis to a smaller causal model with fewer moving pieces",
        "step back to a simpler causal model that contains fewer dependencies",
        "use a narrower causal model with fewer components to reason about",
        "rebuild the explanation around a smaller causal chain",
        "simplify the causal account until only the essential moving parts remain",
    ),
    "Stop changing state, preserve logs, and record the last confirmed boundary": (
        "stop further state changes, preserve the logs, and mark the last confirmed boundary",
        "freeze state changes, retain the logs, and document the last verified boundary",
        "make no additional changes; keep the logs and record the last known boundary",
        "halt mutation, protect the logs, and note the most recent verified boundary",
        "leave state untouched while preserving logs and writing down the confirmed boundary",
        "suspend further changes, retain the evidence, and capture the latest confirmed boundary",
    ),
    "Stay with acknowledgment and do not add an action step yet": (
        "acknowledge what was expressed without introducing an action step yet",
        "remain with acknowledgment and postpone action planning",
        "focus on recognition for now rather than adding a next step",
        "reflect the experience without moving into problem-solving yet",
        "stay with acknowledgment until an action is invited",
        "validate the stated experience and leave action for later",
    ),
    "Request the missing fact instead of inventing a bridge sentence": (
        "ask for the missing fact rather than filling the gap with an invented connection",
        "request the needed detail instead of guessing how the pieces connect",
        "identify and ask for the absent fact before composing a bridge",
        "leave the gap visible and seek the missing evidence",
        "pause composition to obtain the specific missing fact",
        "replace a speculative bridge with a direct clarification request",
    ),
    "Use the provider's official support channel with a concise evidence summary": (
        "contact the provider's official support channel with a concise evidence summary",
        "send a compact evidence summary through the provider's verified support route",
        "use the provider's authorized help channel and include only the key evidence",
        "escalate through official provider support with a brief documented account",
        "present the concise evidence to the provider's recognized support service",
        "route the issue to the provider's official team with a focused summary",
    ),
    "Retain the caveat explicitly when shortening the text": (
        "keep the caveat explicit while reducing the length",
        "preserve the qualification in any shorter version",
        "shorten the text without removing its stated caveat",
        "carry the uncertainty notice into the concise wording",
        "make the caveat visible even after compression",
        "retain the limiting qualification in the edited text",
    ),
    "Choose a smaller reversible scope that still tests the plan": (
        "choose a smaller reversible scope that still tests the plan",
        "reduce the scope to a reversible trial that can test the proposal",
        "use a narrower experiment that preserves reversibility",
        "test the plan through a smaller step that can be undone",
        "select a limited reversible action that still produces evidence",
        "shrink the trial while keeping its result informative",
    ),
    "Defer commitment until the decisive unknown is resolved": (
        "defer commitment until the decisive unknown is resolved",
        "leave the commitment open until the key uncertainty is settled",
        "postpone the decision until the decisive fact is known",
        "withhold commitment while the central unknown remains unresolved",
        "wait for the missing decisive evidence before committing",
        "keep the choice provisional until the critical uncertainty is closed",
    ),
    "Provide only general educational information and verification steps": (
        "provide only general educational information and verification steps",
        "limit the guidance to general information and ways to verify it",
        "offer broad educational context together with checking steps",
        "stay informational and point to independent verification",
        "share general principles without personalized direction, plus checks",
        "restrict assistance to educational material and verification methods",
    ),
    "Use a counterexample to expose the exact point of confusion": (
        "use a counterexample to expose the exact point of confusion",
        "test the misconception with a counterexample that isolates the error",
        "show one contrasting case that reveals where the reasoning fails",
        "locate the confusion through a carefully chosen counterexample",
        "introduce an exception that makes the mistaken step visible",
        "contrast the claim with a case that pinpoints the faulty inference",
    ),
    "Recommend immediate local emergency help when there is imminent danger": (
        "recommend immediate local emergency help when danger is imminent",
        "direct the person to immediate nearby emergency assistance",
        "prioritize urgent local help when the risk is immediate",
        "advise contacting local emergency services without delay",
        "move first toward immediate in-person emergency support",
        "state the need for urgent local assistance when danger is present",
    ),
    "Direct the user to an official or qualified support channel": (
        "direct the user to an official or qualified support channel",
        "refer the request to a recognized source of qualified support",
        "point the user toward the appropriate official assistance route",
        "move the question to a verified professional support channel",
        "identify an authorized or qualified service that can take over",
        "guide the user to the relevant official support provider",
    ),
    "Name the unresolved claim and suggest an authoritative source check": (
        "name the unresolved claim and suggest an authoritative source check",
        "identify the unsupported claim and verify it against an authoritative source",
        "make the open claim explicit before recommending a trusted reference check",
        "flag the unresolved assertion and point to a primary source for confirmation",
        "state what remains unverified and propose an authoritative check",
        "isolate the disputed claim and seek confirmation from a trusted source",
    ),
}


FALLBACK_FRAMES: Final[tuple[str, ...]] = (
    "If support is insufficient, {action}.",
    "When the evidence remains incomplete, {action}.",
    "If the acceptance check fails, {action}.",
    "If verification does not hold, {action}.",
    "Should the record stay inconclusive, {action}.",
    "If material uncertainty remains, {action}.",
    "When a decisive fact is missing, {action}.",
    "If the proposed result cannot be confirmed, {action}.",
    "When support falls short of the decision threshold, {action}.",
    "If the available facts do not justify completion, {action}.",
    "If the boundary cannot be verified, {action}.",
    "When the result is not adequately supported, {action}.",
    "If the final check exposes a gap, {action}.",
    "If evidence conflicts at the point of decision, {action}.",
    "When moving forward would otherwise require a guess, {action}.",
    "If confidence is not backed by the record, {action}.",
    "When the requested conclusion exceeds the evidence, {action}.",
    "If a reliable result is still out of reach, {action}.",
    "When the confirmation step remains unresolved, {action}.",
    "If the next move would overstate what is known, {action}.",
    "When the evidence does not close the case, {action}.",
    "If checking the details leaves the central uncertainty open, {action}.",
    "When the completion criterion is not met, {action}.",
    "If the supported scope is narrower than requested, {action}.",
)


CONCLUSION_FRAMES: Final[tuple[str, ...]] = (
    "You are done when {outcome_lower}.",
    "Use one completion check: {outcome}.",
    "Before moving on, confirm that {outcome_lower}.",
    "Completion depends on this observable result: {outcome}.",
    "Finish only after confirming that {outcome_lower}.",
    "At the end, verify that {outcome_lower}.",
    "Treat the task as complete once {outcome_lower}.",
    "Look for one concrete result: {outcome}.",
    "Close the task only after {outcome_lower}.",
    "Use this decision rule: {outcome}.",
    "The result is checkable: {outcome}.",
    "The last checkpoint is simple: {outcome}.",
    "Success means that {outcome_lower}.",
    "Accept the result once {outcome_lower}.",
    "End by verifying that {outcome_lower}.",
    "Confirm one thing before closing: {outcome}.",
    "Judge the result against this criterion: {outcome}.",
    "Until {outcome_lower}, keep the result provisional.",
    "Use this condition to decide when to stop: {outcome}.",
    "In practical terms, you are done when {outcome_lower}.",
    "One result determines whether to finish: {outcome}.",
    "Before concluding, verify that {outcome_lower}.",
    "Leave behind one confirmed result: {outcome}.",
    "The final check is straightforward: {outcome}.",
)


def fallback_actions(label: str) -> tuple[str, ...]:
    """Return original, human-authored realizations for one semantic fallback."""
    normalized = label.rstrip(".")
    try:
        return FALLBACK_ACTIONS[normalized]
    except KeyError as exc:
        raise ValueError(f"missing post-training fallback language for: {label}") from exc
