from __future__ import annotations

from typing import Final


FAMILY_OPENINGS: Final[dict[str, tuple[str, ...]]] = {
    "practical_action": (
        "Let's turn the request into one concrete next step.",
        "The immediate task is to make the requested change safely.",
        "A useful answer should identify what can be done now.",
        "The request is ready for a specific, confirmed action.",
        "The available details point to a manageable next move.",
        "Start with an action that can be checked and reversed.",
        "The answer should make the next operational choice clear.",
        "One supported action can move this request forward.",
    ),
    "explanation_learning": (
        "Start with the mechanism the learner needs to see.",
        "The explanation should connect the idea to a usable example.",
        "A clear answer can move from the known rule to its application.",
        "The learner needs one visible link between cause and result.",
        "This concept becomes useful when it can be applied elsewhere.",
        "The response should make the reasoning easier to transfer.",
        "Begin with what is understood, then expose the missing step.",
        "A small example can reveal how the principle actually works.",
    ),
    "troubleshooting": (
        "Treat the failure as an observation that can be tested.",
        "The next diagnostic step should narrow the source of the problem.",
        "Begin with the smallest test that can reproduce the symptom.",
        "A useful diagnosis changes one condition at a time.",
        "The evidence should distinguish the symptom from its cause.",
        "Start by locating the last state known to work.",
        "The failure can be investigated without changing everything at once.",
        "A focused check should reveal which assumption fails first.",
    ),
    "writing_transformation": (
        "The source material sets the limits of the rewrite.",
        "The edit should improve clarity without changing the underlying claim.",
        "A faithful rewrite preserves meaning while changing presentation.",
        "The response can be reshaped without adding a new commitment.",
        "Start by identifying what the revised text must retain.",
        "The transformation should make the original message easier to use.",
        "A careful edit separates wording changes from factual changes.",
        "The revised version should remain traceable to the source.",
    ),
    "planning_comparison": (
        "A useful comparison starts by narrowing the decision.",
        "The plan should distinguish requirements from preferences.",
        "The choice becomes clearer once the decisive criteria are visible.",
        "Begin with the options that satisfy the non-negotiable conditions.",
        "A practical plan needs both a preferred route and a fallback.",
        "The decision should remain adjustable while uncertainty is high.",
        "The available options can be compared through concrete trade-offs.",
        "A good recommendation explains why one path fits better.",
    ),
    "conversation_empathy": (
        "The response should meet the feeling before proposing change.",
        "Begin by recognizing what the person is carrying right now.",
        "A helpful reply can acknowledge the experience without taking it over.",
        "The immediate need is understanding, not premature problem-solving.",
        "The conversation can make room for both difficulty and agency.",
        "A grounded reply should reflect the experience in plain language.",
        "Start with recognition and let the next step stay proportionate.",
        "The answer should support the person without assuming their motives.",
    ),
    "safety_uncertainty": (
        "Safety determines the scope of the answer.",
        "The response should reduce risk before expanding the advice.",
        "Begin by making the boundary of safe assistance explicit.",
        "Uncertainty matters here because the consequences may be significant.",
        "The safest answer separates useful information from consequential action.",
        "The response should protect the requester without overstating certainty.",
        "A clear safety boundary is more useful than a confident guess.",
        "The first priority is to avoid turning missing context into harm.",
    ),
}


FAMILY_ACTION_FRAMES: Final[dict[str, tuple[str, ...]]] = {
    "practical_action": (
        "For {subject}, the next concrete move is to {intent}.",
        "I would use the confirmed details to {intent} for {subject}.",
        "The request can advance through one supported attempt to {intent} for {subject}.",
        "A safe first move is to {intent} for {subject}.",
        "The available record supports a plan to {intent} for {subject}.",
        "The response should name how to {intent} for {subject} and what happens next.",
        "For {subject}, begin with the smallest supported attempt to {intent}.",
        "The practical recommendation is to {intent} for {subject}.",
    ),
    "explanation_learning": (
        "For {subject}, the response should help the learner {intent}.",
        "I would build the explanation around one attempt to {intent}.",
        "{subject_cap} becomes clearer when the learner can {intent}.",
        "The next teaching move is to {intent} and then check transfer.",
        "A worked response can {intent} without adding unsupported claims.",
        "Use the known facts to {intent}, keeping {subject} as the example.",
        "The explanation should make it possible to {intent}.",
        "Connect the definition to an opportunity to {intent}.",
    ),
    "troubleshooting": (
        "For {subject}, begin by trying to {intent}.",
        "The diagnostic next step is to {intent} for {subject}.",
        "Use the current evidence to {intent} before changing another variable.",
        "I would {intent} for {subject} and record what the test changes.",
        "A narrow test can {intent} for {subject} without disturbing unrelated state.",
        "The investigation should {intent} and preserve the result for comparison.",
        "To isolate the failure, first {intent} for {subject}.",
        "The next check should {intent} using the smallest reproducible setup.",
    ),
    "writing_transformation": (
        "For {subject}, the edit should {intent}.",
        "I would {intent} while keeping {subject} faithful to its source.",
        "The revised text can {intent} without introducing a new fact.",
        "Use the source as the reference point and {intent} for {subject}.",
        "The transformation should {intent} while preserving the original scope.",
        "For this version, {intent} and keep every material claim traceable.",
        "The response can {intent} for {subject} without changing its commitments.",
        "I would make the wording easier to use, then {intent}.",
    ),
    "planning_comparison": (
        "For {subject}, the decision can advance by trying to {intent}.",
        "The planning step is to {intent} for {subject}.",
        "I would use the stated priorities to {intent} for {subject}.",
        "A useful comparison can {intent} while keeping alternatives open.",
        "The recommendation should {intent} for {subject} and expose the trade-off.",
        "Begin with the hard criteria, then {intent} for {subject}.",
        "The available options support one bounded attempt to {intent}.",
        "For this decision, {intent} and retain a workable fallback.",
    ),
    "conversation_empathy": (
        "For {subject}, the response should {intent} before proposing a solution.",
        "I would {intent} for {subject} and leave room for the person's own view.",
        "The next reply can {intent} without forcing an action step.",
        "A supportive response should {intent} for {subject} in direct language.",
        "Start by listening for the immediate need, then {intent}.",
        "The answer can {intent} while preserving the person's agency.",
        "For this conversation, {intent} and keep any next step small.",
        "The response should {intent} without assuming an unstated cause.",
    ),
    "safety_uncertainty": (
        "For {subject}, the response should {intent} without taking consequential action.",
        "I would {intent} for {subject} and state what cannot be verified.",
        "The safest useful response can {intent} while withholding unsupported certainty.",
        "Begin by identifying the immediate risk, then {intent} for {subject}.",
        "The answer should {intent} and direct any urgent need to qualified help.",
        "For this request, {intent} without asking for sensitive information.",
        "A bounded response can {intent} while keeping the safety threshold visible.",
        "The appropriate next move is to {intent} for {subject} within a limited scope.",
    ),
}


FAMILY_CONSTRAINT_FRAMES: Final[dict[str, tuple[str, ...]]] = {
    "practical_action": (
        "Before acting, keep this limit in place: {constraint}.",
        "The action must stay within this condition: {constraint}.",
        "One operating rule cannot be relaxed: {constraint}.",
        "The next step remains valid only if this holds: {constraint}.",
        "Execution stops at the following boundary: {constraint}.",
        "Any proposed change must preserve this requirement: {constraint}.",
        "Use this condition to rule out unsafe actions: {constraint}.",
        "The practical plan is constrained by one fixed rule: {constraint}.",
    ),
    "explanation_learning": (
        "The explanation must respect this evidence limit: {constraint}.",
        "Do not cross this boundary while teaching the concept: {constraint}.",
        "The example remains valid only under this rule: {constraint}.",
        "Keep the reasoning inside this stated condition: {constraint}.",
        "The lesson cannot rely on anything beyond this limit: {constraint}.",
        "Use this requirement to check every explanatory step: {constraint}.",
        "The learner should not be asked to assume more than this: {constraint}.",
        "One factual boundary governs the explanation: {constraint}.",
    ),
    "troubleshooting": (
        "Every diagnostic action must respect this limit: {constraint}.",
        "Do not advance the test beyond this boundary: {constraint}.",
        "The investigation keeps one condition fixed: {constraint}.",
        "Reject any diagnostic step that violates this rule: {constraint}.",
        "The test sequence remains safe only while this holds: {constraint}.",
        "Preserve this requirement throughout the diagnosis: {constraint}.",
        "One boundary controls how far the investigation can go: {constraint}.",
        "Use this condition as the stop rule for each test: {constraint}.",
    ),
    "writing_transformation": (
        "The rewrite must preserve this limit: {constraint}.",
        "No edit may cross the following boundary: {constraint}.",
        "Judge every wording change against this requirement: {constraint}.",
        "The transformed text remains faithful only if this holds: {constraint}.",
        "Keep this rule visible during revision: {constraint}.",
        "The new wording cannot override this condition: {constraint}.",
        "Use this boundary to reject unsupported additions: {constraint}.",
        "One source constraint governs the final version: {constraint}.",
    ),
    "planning_comparison": (
        "The decision must continue to satisfy this condition: {constraint}.",
        "Any preferred option remains subject to this limit: {constraint}.",
        "Do not trade away the following requirement: {constraint}.",
        "The comparison excludes choices that violate this rule: {constraint}.",
        "Keep this boundary fixed while weighing the options: {constraint}.",
        "The plan is acceptable only while this remains true: {constraint}.",
        "Use this condition as a hard filter: {constraint}.",
        "One non-negotiable rule shapes the recommendation: {constraint}.",
    ),
    "conversation_empathy": (
        "The reply should honor this interpersonal limit: {constraint}.",
        "Do not move the conversation beyond this boundary: {constraint}.",
        "The support remains appropriate only if this holds: {constraint}.",
        "Keep this condition in view while responding: {constraint}.",
        "The conversation should not override this requirement: {constraint}.",
        "Use this boundary to keep the response proportionate: {constraint}.",
        "One relational limit governs the next reply: {constraint}.",
        "The response must leave this condition intact: {constraint}.",
    ),
    "safety_uncertainty": (
        "The safety boundary is explicit: {constraint}.",
        "Do not provide assistance that violates this rule: {constraint}.",
        "The response must stop before crossing this limit: {constraint}.",
        "Any useful guidance remains subject to this condition: {constraint}.",
        "Use this requirement to define the safe scope: {constraint}.",
        "The uncertainty cannot justify ignoring this boundary: {constraint}.",
        "One protective rule governs the response: {constraint}.",
        "The answer is safe only while this remains true: {constraint}.",
    ),
}


RESPONSE_ORDERS: Final[tuple[tuple[str, ...], ...]] = (
    ("opening", "action", "constraint", "conclusion", "fallback"),
    ("opening", "constraint", "action", "conclusion", "fallback"),
    ("action", "opening", "constraint", "conclusion", "fallback"),
    ("action", "constraint", "opening", "conclusion", "fallback"),
    ("constraint", "opening", "action", "conclusion", "fallback"),
    ("constraint", "action", "opening", "conclusion", "fallback"),
    ("opening", "action", "constraint", "fallback", "conclusion"),
    ("opening", "constraint", "action", "fallback", "conclusion"),
    ("action", "opening", "constraint", "fallback", "conclusion"),
    ("action", "constraint", "opening", "fallback", "conclusion"),
    ("constraint", "opening", "action", "fallback", "conclusion"),
    ("constraint", "action", "opening", "fallback", "conclusion"),
)


# These are original Complexity formulations.  The source fallback remains the
# semantic contract; these variants change only its surface realization.
FALLBACK_ACTIONS: Final[dict[str, tuple[str, ...]]] = {
    "Pause before commitment and preserve the current confirmed state": (
        "pause before making a commitment and leave the latest confirmed state intact",
        "hold back commitment while keeping the current verified state unchanged",
        "defer commitment and preserve the most recent confirmed state",
        "keep the decision open without altering what has already been confirmed",
        "avoid committing yet and protect the last verified state",
        "leave the confirmed state untouched until commitment is justified",
    ),
    "Return to a smaller causal model with fewer moving parts": (
        "return to a smaller causal model with fewer interacting parts",
        "reduce the analysis to a smaller causal model with fewer moving pieces",
        "step back to a simpler causal model that contains fewer dependencies",
        "use a narrower causal model with fewer components to reason about",
        "rebuild the explanation around a smaller causal chain",
        "simplify the causal account until only the essential moving parts remain",
    ),
    "Stop changing state, preserve logs, and record the last confirmed boundary": (
        "stop further state changes, preserve the logs, and mark the last confirmed boundary",
        "freeze state changes, retain the logs, and document the last verified boundary",
        "make no additional changes; keep the logs and record the last known boundary",
        "halt mutation, protect the logs, and note the most recent verified boundary",
        "leave state untouched while preserving logs and writing down the confirmed boundary",
        "suspend further changes, retain the evidence, and capture the latest confirmed boundary",
    ),
    "Stay with acknowledgment and do not add an action step yet": (
        "acknowledge what was expressed without introducing an action step yet",
        "remain with acknowledgment and postpone action planning",
        "focus on recognition for now rather than adding a next step",
        "reflect the experience without moving into problem-solving yet",
        "keep the response at acknowledgment until an action is invited",
        "validate the stated experience and leave action for later",
    ),
    "Request the missing fact instead of inventing a bridge sentence": (
        "ask for the missing fact rather than filling the gap with an invented connection",
        "request the needed detail instead of guessing how the pieces connect",
        "identify and ask for the absent fact before composing a bridge",
        "leave the gap visible and seek the missing evidence",
        "pause composition to obtain the specific missing fact",
        "replace a speculative bridge with a direct clarification request",
    ),
    "Use the provider's official support channel with a concise evidence summary": (
        "contact the provider's official support channel with a concise evidence summary",
        "send a compact evidence summary through the provider's verified support route",
        "use the provider's authorized help channel and include only the key evidence",
        "escalate through official provider support with a brief documented account",
        "present the concise evidence to the provider's recognized support service",
        "route the issue to the provider's official team with a focused summary",
    ),
    "Retain the caveat explicitly when shortening the text": (
        "keep the caveat explicit while reducing the length",
        "preserve the qualification in any shorter version",
        "shorten the text without removing its stated caveat",
        "carry the uncertainty notice into the concise wording",
        "make the caveat visible even after compression",
        "retain the limiting qualification in the edited text",
    ),
    "Choose a smaller reversible scope that still tests the plan": (
        "choose a smaller reversible scope that still tests the plan",
        "reduce the scope to a reversible trial that can test the proposal",
        "use a narrower experiment that preserves reversibility",
        "test the plan through a smaller step that can be undone",
        "select a limited reversible action that still produces evidence",
        "shrink the trial while keeping its result informative",
    ),
    "Defer commitment until the decisive unknown is resolved": (
        "defer commitment until the decisive unknown is resolved",
        "leave the commitment open until the key uncertainty is settled",
        "postpone the decision until the decisive fact is known",
        "withhold commitment while the central unknown remains unresolved",
        "wait for the missing decisive evidence before committing",
        "keep the choice provisional until the critical uncertainty is closed",
    ),
    "Provide only general educational information and verification steps": (
        "provide only general educational information and verification steps",
        "limit the response to general guidance and ways to verify it",
        "offer broad educational context together with checking steps",
        "keep the answer informational and point to independent verification",
        "share general principles without personalized direction, plus checks",
        "restrict assistance to educational material and verification methods",
    ),
    "Use a counterexample to expose the exact point of confusion": (
        "use a counterexample to expose the exact point of confusion",
        "test the misconception with a counterexample that isolates the error",
        "show one contrasting case that reveals where the reasoning fails",
        "locate the confusion through a carefully chosen counterexample",
        "introduce an exception that makes the mistaken step visible",
        "contrast the claim with a case that pinpoints the faulty inference",
    ),
    "Recommend immediate local emergency help when there is imminent danger": (
        "recommend immediate local emergency help when danger is imminent",
        "direct the person to immediate nearby emergency assistance",
        "prioritize urgent local help when the risk is immediate",
        "advise contacting local emergency services without delay",
        "move first toward immediate in-person emergency support",
        "state the need for urgent local assistance when danger is present",
    ),
    "Direct the user to an official or qualified support channel": (
        "direct the user to an official or qualified support channel",
        "refer the request to a recognized source of qualified support",
        "point the user toward the appropriate official assistance route",
        "move the question to a verified professional support channel",
        "identify an authorized or qualified service that can take over",
        "guide the user to the relevant official support provider",
    ),
    "Name the unresolved claim and suggest an authoritative source check": (
        "name the unresolved claim and suggest an authoritative source check",
        "identify the unsupported claim and verify it against an authoritative source",
        "make the open claim explicit before recommending a trusted reference check",
        "flag the unresolved assertion and point to a primary source for confirmation",
        "state what remains unverified and propose an authoritative check",
        "isolate the disputed claim and seek confirmation from a trusted source",
    ),
}


FALLBACK_FRAMES: Final[tuple[str, ...]] = (
    "If support is insufficient, {action}.",
    "When the evidence remains incomplete, {action}.",
    "If the acceptance check fails, {action}.",
    "If verification does not hold, {action}.",
    "Should the record stay inconclusive, {action}.",
    "If material uncertainty remains, {action}.",
    "When a decisive fact is missing, {action}.",
    "If the proposed result cannot be confirmed, {action}.",
    "When support falls short of the decision threshold, {action}.",
    "If the available facts do not justify completion, {action}.",
    "If the boundary cannot be verified, {action}.",
    "When the result is not adequately supported, {action}.",
    "If the final check exposes a gap, {action}.",
    "If evidence conflicts at the point of decision, {action}.",
    "When the answer would otherwise require a guess, {action}.",
    "If confidence is not backed by the record, {action}.",
    "When the requested conclusion exceeds the evidence, {action}.",
    "If a reliable result is still out of reach, {action}.",
    "When the confirmation step remains unresolved, {action}.",
    "If the next move would overstate what is known, {action}.",
    "When the evidence does not close the case, {action}.",
    "If review leaves the central uncertainty open, {action}.",
    "When the completion criterion is not met, {action}.",
    "If the supported scope is narrower than requested, {action}.",
)


CONCLUSION_FRAMES: Final[tuple[str, ...]] = (
    "The required result is clear: {outcome}.",
    "Use this as the completion criterion: {outcome}.",
    "The acceptance check is explicit: {outcome}.",
    "Completion depends on one observable result: {outcome}.",
    "The response is ready only after confirming this: {outcome}.",
    "The final review should establish the following: {outcome}.",
    "Treat the task as complete when this result holds: {outcome}.",
    "The evidence should support this concrete outcome: {outcome}.",
    "Close the task only after verifying this result: {outcome}.",
    "The decision rule is whether this has been achieved: {outcome}.",
    "A valid answer produces this checkable result: {outcome}.",
    "The last checkpoint is straightforward: {outcome}.",
    "Success is bounded by this observable condition: {outcome}.",
    "The result can be accepted once this is true: {outcome}.",
    "Verification should end with this finding: {outcome}.",
    "The closing evidence must demonstrate this: {outcome}.",
    "Resolve the request against this criterion: {outcome}.",
    "The answer remains provisional until this is confirmed: {outcome}.",
    "Use the following condition to decide whether to finish: {outcome}.",
    "The practical definition of done is this: {outcome}.",
    "One result determines acceptance: {outcome}.",
    "Before concluding, verify this outcome: {outcome}.",
    "The response should leave behind this confirmed result: {outcome}.",
    "The final evidence test is the following: {outcome}.",
)


def fallback_actions(label: str) -> tuple[str, ...]:
    """Return original, human-authored realizations for one semantic fallback."""
    normalized = label.rstrip(".")
    try:
        return FALLBACK_ACTIONS[normalized]
    except KeyError as exc:
        raise ValueError(f"missing post-training fallback language for: {label}") from exc
